### ISSUE TITLE
Проблема с чайником Redmond RK-M171S-E

### ISSUE THREAD

**Issue by runnerfanspb** [mavrikkk/ha_kettler#1]
Спасибо за компонент способный присоединить технику Redmond. В наличии имеется чайник Redmond RK-M171S-E , все сделал по инструкции. Hassio  видит данный чайник, но почему - в графе состояние пишет не известно, так же не включает и не выключает его. Извечный вопрос, что делать? Куда копать?
В конфиге прописывал следующее:
r4s_kettler:
  device: 'hci0'
  mac: 'C5:57:7D:50:23:51'
  password: 'ab64e6f700f75d65'
  scan_interval: 90

**Comment by mavrikkk** [comment]
Мой модуль заточен под G200S.
Если вы прочтете вступление в моей статье на хабре (https://habr.com/en/post/412583/), то узнаете, что у наших чайников отличаются команды. Заодно там же есть ссылка на статью автора, который занимался вашим чайником. Вполне реально в моем коде заменить команды на нужные вам.

**Comment by runnerfanspb** [comment]
Понял,спасибо. Вам успехов и хорошего дня

**Comment by 3AXAPOB** [comment]
"Вполне реально в моем коде заменить команды на нужные вам."

Подскажите как это сделать? Что и где нужно заменить?
