### ISSUE TITLE
подключение G202S

### ISSUE THREAD

**Issue by anaderi** [mavrikkk/ha_kettler#2]
купил G202S, поставил ha_kettler в HACS, посмотрел MAC чайника через bluetoothctl, вписал его в конфиг вместе со случайным паролем. нажал на чайнике кнопку спаривания и рестартанул hass. 
в логах получаю 

> Feb  3 23:34:05 raspberrypi hass[667]: 2020-02-03 23:34:05 ERROR (MainThread) [custom_components.r4s_kettler] error connect

в чем может быть проблема?

**Comment by anaderi** [comment]
да, и до этого появляется еще сообщение 

> ERROR (MainThread) [custom_components.r4s_kettler] error first connect

во время того, как на чайнике горят огоньки, подтверждающие его готовность спариваться )

**Comment by anaderi** [comment]
эти команды до рестарта выполнил:

> sudo setcap cap_net_raw+ep /usr/bin/hcitool
> sudo setcap cap_net_raw+ep /bin/hciconfig

**Comment by anaderi** [comment]
проделал еще одно действие: рестартовал bluetoothctl, и спарился с чайником через него.
результат: после рестарта hass:

> Feb  4 00:24:47 raspberrypi hass[5200]: 2020-02-04 00:24:47 INFO (MainThread) [homeassistant.setup] Setting up r4s_kettler
> Feb  4 00:24:47 raspberrypi kernel: [180548.111957] Bluetooth: hci0: Frame reassembly failed (-84)
> Feb  4 00:24:47 raspberrypi kernel: [180548.111979] Bluetooth: hci0: Frame reassembly failed (-84)
> Feb  4 00:24:47 raspberrypi kernel: [180548.111988] Bluetooth: hci0: advertising data len corrected
> Feb  4 00:24:47 raspberrypi kernel: [180548.112264] Bluetooth: hci0: Frame reassembly failed (-84)
> Feb  4 00:24:47 raspberrypi kernel: [180548.112274] Bluetooth: hci0: Frame reassembly failed (-84)
> Feb  4 00:25:00 raspberrypi hass[5200]: 2020-02-04 00:25:00 ERROR (MainThread) [custom_components.r4s_kettler] error first connect

ошибки подключения как раньше исчезли, но "Frame reassembly" стало появляться в логах. 

Версия прошивки чайника 3.12

**Comment by mavrikkk** [comment]
1. Перечислите ваш программно аппаратный комплекс для homeassistant:
а. вижу, что raspberry, но как? virtualenv, docker, hassio, hassos?
б. какой блютус? встроенный или внешний по усб?
в. версия малинки, версия linux, если не hassos
2. Не оставили подключение в bluetoothctl? Если осталось - удалите подключение и забудьте устройство.

**Comment by anaderi** [comment]
1. комплекс: virtialenv, блютус встроенный, версия малинки 3B+ v1.2, Linux raspberrypi 4.19.75-v7+
2. устройство из bluetoothctl удалил
> [custom_components.r4s_kettler] error connect
после рестарта hass осталось

**Comment by mavrikkk** [comment]
1. Встроенный блютус - это зло. У меня с ним нестабильно работало. На офф форумах малинки на него тоже постоянно жалуются. Работать с ним все равно должно, но очень нестабильно. Рекомендую свисток.

2. Рекомендацию из моей статьи пробовали?
Если gatttool не желает подключаться к чайнику (такое возможно при первом подключении к неизвестным устройствам), то попробуйте выполнить поиск чайника средствами os до подключения модуля:

sudo hciconfig device reset
sudo timeout 1 hcitool lescan

device — id вашего блютус устройства (например, hci0). 

Убедитесь, что мак адрес вашего чайника есть в списке найденных устройств. После этого:

sudo hcitool lewladd mac
sudo hcitool lerladd mac

mac — мак адрес вашего чайника

3. После этого, если все прошло успешно, перевести чайник в режим сопряжения. Как только на нем замигают огоньки - перезапустить HA для коннекта к чайнику.

**Comment by anaderi** [comment]
> sudo hcitool lewladd D5:70:31:0C:4B:9C
> sudo hcitool lewladd D5:70:31:0C:4B:9C
> Can't add to white list: Input/output error(5)

но после этого пункт (3) прошел успешно!
посмотрим сколько он продержится без BT-свистка )

**Comment by mavrikkk** [comment]
продержится ровно столько, сколько продержатся ваши нервы )))
Удачи.

**Comment by anaderi** [comment]
действительно спустя какое-то время подключение отваливается. купил свисток. теперь есть два устройства hci0 (USB) и hci1 (UART). но `gatttool -I -t random -i hci0 -b D5:70:31:0C:4B:9C` и затем `connect` дает 

> Attempting to connect to D5:70:31:0C:4B:9C
> Error: connect: No route to host (113)

если заменить hci0 на hci1 - то все работает. в чем может быть дело?

**Comment by mavrikkk** [comment]
а вы выполнили рекомендуемые шаги?
те, что я выше писал?

sudo hciconfig device reset
sudo timeout 1 hcitool lescan
sudo hcitool lewladd mac
sudo hcitool lerladd mac

ибо в офф документации к gatttool сказано:
If you get a connect: No route to host (113) , that means the device is not advertising, you've used the wrong address or you haven't run sudo hcitool lescan before opening gatttool

**Comment by anaderi** [comment]
поменял свисток на Baseus и все стало норм.
