### ISSUE TITLE
RK-G202S support

### ISSUE THREAD

**Issue by r-vit** [mavrikkk/ha_kettler#20]
Можете добавить поддержку RK-G202S? По-моему, он не отличается от RK-G200S (в старых версиях работал).
Сейчас при попытке добавить интеграцию не дает ввести вручную mac-адрес, а выпадающий список пуст. 
Ручное добавление в SUPPORTED_DEVICES 'RK-G202S':1, в файл __init__.py ситуацию не меняет

**Comment by mavrikkk** [comment]
> он не отличается от RK-G200S (в старых версиях работал).

значит ищите проблему у себя.
в SUPPORTED_DEVICES я его добавить могу, но раз это не помогает, значит у вас что то с блютусом.  я запускаю сканирование устройств на 3 секунды...этого более чем достаточно.
в линуксе блютус работает только от рута.

1. какая у вас система? 
2. как настроен homeassistant? как hassOS или hassio или через virtual env? или просто сервисом?
3. рекомендации самого HA по работе с блютусом выполнили?

https://www.home-assistant.io/integrations/bluetooth_le_tracker/
и
https://www.home-assistant.io/integrations/mitemp_bt/

**Comment by r-vit** [comment]
Система - Home Assistant, установленный в virtualenv в Arch Linux
Предыдущие версии плагина, где mac-адрес чайника нужно было вводить вручную, работали более-менее нормально. Датчики MiFlora работают идеально, поэтому делаю вывод, что BT-стек работает.
При сканировании через bluetoothctl чайник находится, причем создает немало трафика.

Может, до прояснения ситуации стоит вернуть возможность указания mac-адреса вручную?

**Comment by mavrikkk** [comment]
> установленный в virtualenv в Arch Linux

читайте ссылки выше!
некоторые команды (в частности которыми я пользуюсь) работают от рута! у меня была конфигурация похожая на вашу...куча проблем и движений ручками...в частности и с блютусом!
вам нужно разрешить работу с блютусом без рута...в ссылках выше все есть.

**Comment by mavrikkk** [comment]
на тот же арч можно без проблем hassio накатить. в доккере работать будет...все работает из коробки...есть нативные бекапы и куча всего.

**Comment by r-vit** [comment]
да, я уже работал с hassio - не устраивает по многим причинам

права для доступа к BT пользователям предоставлены - всё было сделано изначально для MiFlora

**Comment by mavrikkk** [comment]
из первой ссылки:
Before you get started with this platform, please note that:

This platform is incompatible with Windows
This platform requires access to the Bluetooth stack, see Rootless Setup section for further information
если это, как вы говорите, уже есть, то еще остается:

On other Linux systems:
Preferred solution: Install the bluepy and btlewrap library (via pip). When using a virtual environment, make sure to use install the library in the right one.
Fallback solution: Install btlewrap library (via pip) and gatttool via your package manager. Depending on the distribution, the package name might be: bluez, bluetooth or bluez-deprecated.

**Comment by r-vit** [comment]
Это всё уже сделано. Меня смущает, что версия с ручным вводом mac-адреса работала. В данной ситуации всё упирается в то, что сканирование либо не работает, либо не находит ничего. Я буду разбираться с правами доступа. Но, может, все-таки вернуть возможность ручного ввода mac-адреса?

**Comment by mavrikkk** [comment]
> Но, может, все-таки вернуть возможность ручного ввода mac-адреса?

нет. если я верну ручной ввод, то отключится автозаполнение.

> Меня смущает, что версия с ручным вводом mac-адреса работала
1. а устройства блютус заполняются? hci0, hci1
2. что кажет лог HA?
3. если ничего не кажет, то отключите все try в config flow

**Comment by mavrikkk** [comment]
вот в этой функции уберите все try

def get_devices(self):

**Comment by r-vit** [comment]
hci0 заполняется, в логе ничего нет

сейчас добавил (setcap) права для bluepy-helper, сканирование le устройств (blescan) от пользователя выполняется нормально. 

спасибо, попробую, если с правами не получится

**Comment by r-vit** [comment]
да, добавление setcap для bluepy-helper помогло

возможно, стоит отметить в инструкции

**Comment by mavrikkk** [comment]
> возможно, стоит отметить в инструкции

таких моментов уже с десяток )) и все связаны вот с такими конфигурациями...в hassio все работает само и из коробки...
предполагаю, что кто лазит ручками - сможет разобраться...ну или тут ветку открыть...

отлично, что у вас заработало! добавлю ваш чайник в список при обновлении.
постараюсь также не забыть обновить ридми
