### ISSUE TITLE
Нет связи с чайником после создания интеграции

### ISSUE THREAD

**Issue by Aroxyson** [mavrikkk/ha_kettler#21]
После создания интеграции (автоматом определился интерфейс,mac), появились сущности чайника, сенсора, подсветки. Но связи с ними нет - состояние "недоступно". До этого стоял старый компонент r4s_kettler, все работало.

В логах при этом:
`five attempts of firstConnect failed`
и далее
`five attempts of modeUpdate failed`

Режим сопряжения на чайнике пробовал включать на разных этапах. Вообще, в какой момент по уму нужно это делать? И нужно ли? На прошлой конфигурации уже не помню, как завелось.

Также замечаю зависания веб-морды HA как в соседней ветке, но отследить, когда именно зависает, пока не удалось.

Raspberry Pi 4
Версия HA (Hassio) - 0.109.6
Чайник Kettle RK-G210S

**Comment by mavrikkk** [comment]
> В логах при этом:

у вас самое первое подключение не прошло...скорее всего из за авторизации.



> Вообще, в какой момент по уму нужно это делать? И нужно ли?

в вашем случае правильнее было скопировать ключ из старой конфигурации. Тогда переводить в режим сопряжения вообще не нужно. Но усли старый ключ утерян то порядок такой:
1. Заходите в интеграции, нажимаете добавить, ищете r4s...выбираете
2. в открывшемся через 3-4 сек окне выбираете свое устройство, свой чайник, выставляете частоту обновления, выбираете нужна ли вам подсветка...потом выдумываете пароль из 16 символов...НО не любой!!! пароль в hex формате...то есть там могут быть любые цифры а буквы только маленькие, только латинские и только a-f...После ввода жмете подтвердить.
3. Появится окно с просьбой перевести чайник в режим сопряжения...Именно сейчас нужно зажать кнопку, дождаться пока забегают огоньки и после этого нажать кнопку Подтвердить...чайник должен авторизоваться.

**Comment by Aroxyson** [comment]
Все завелось, спасибо. Проблема была в моменте подключения и допустимых символах. Думаю процесс добавления чайника "для чайников" с тонкостями нужно добавить в readme.
