### ISSUE TITLE
Настройка модулей pybluez, bluepy

### ISSUE THREAD

**Issue by Seegak3** [mavrikkk/ha_kettler#23]
Здравствуйте! В руководстве сказано: "В любой другой конфигурации возможно придется сделать дополнительные настройки: Установить модули для работы с bluetooth (pybluez, bluepy), настроить эти модули так, чтобы они работали без прав root.". Модули установил, но как настроить данные модули для работы без root прав?

**Comment by mavrikkk** [comment]
эта ветка

https://github.com/mavrikkk/ha_kettler/issues/20

плюс гугл

**Comment by tayanov** [comment]
ну бред.
убрал try: exept:
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)

Главное скрипт (после проверки синтаксиса) https://pastebin.com/bmY1TnQ7
 то же викидывал такую ошибку.
Сделал secap для blupy-helper ошибка ушла
менял в консоли python на python3 ошибка опять появляласть
Сделал secap для blupy-helper и для 3 версии. ошибка ушла, скрипт отрабатывает и python k.py и python3 k.py и это от юзера pi.
Но в ха все равно ошибка как сверху ...

**Comment by tayanov** [comment]
перезапустил контейнер в портейнере с переключателем NET_ADMIN. Проблемы с доступом к чайнику ушли. Считаю так же дополнить ридми

**Comment by Seegak3** [comment]
Все рекомендации по HA из указанной ветки выполнил,  добавил права для bluepy-helper, сканирование с помощью blescan от пользователя работает, но все равно отсутствует выбор устройства при добавлении интеграции, так же перезагрузил контейнер HA c переключателем NET_ADMIN - не помогло

**Comment by tayanov** [comment]
> Все рекомендации по HA из указанной ветки выполнил, добавил права для bluepy-helper, сканирование с помощью blescan от пользователя работает, но все равно отсутствует выбор устройства при добавлении интеграции, так же перезагрузил контейнер HA c переключателем NET_ADMIN - не помогло

Убери try exept из config flow. Ха будет более внятные ошибки кидать ...

**Comment by Seegak3** [comment]
> 
> Убери try exept из config flow. Ха будет более внятные ошибки кидать ...

config flow привел к такому виду:
![Безымянный](https://user-images.githubusercontent.com/59684010/82144377-4deecf00-9860-11ea-9143-7177db7fc677.png)
Список устройств при добавлении интеграции появился, чайник RK-M171S удалось добавить в HA, но не работает его включение, при этом после ручного включения чайника обновляется его состояние, а также он отключается из HA

**Comment by mavrikkk** [comment]
> Считаю так же дополнить ридми

какая у вас конфигурация? в какой среде работает HA? вы сами ручками ставили в доккер? просто в hassio я не делал НИЧЕГО из вышеперечисленного...чтобы добавить в ридми, нужно понять, в каком именно случае что делать

**Comment by mavrikkk** [comment]
> Список устройств при добавлении интеграции появился

это хорошая новость, но какой ценой! вы отключили обнаружение и выбор физических устройств блютус...очень странно, что оно у вас не работает. что за железо? модуль блютус? что выдаст команда "hciconfig" набитая в консоли от рута, без рута?



> не работает его включение и отображение текущей температуры

найдите функцию modeOn и уберите оттуда try except чтобы посмотреть, почему именно он падает.


> чайник RK-M171S

как точно он называется, когда при подключении обнаруживается интеграцией?

**Comment by mavrikkk** [comment]
RK-M171S такой чайник не заявлен у меня в поддержке! когда вы подключаете неподдерживаемое оборудование, то тип устройства ставится по умолчанию на мое поколение устройств...серия G200...я его назвал 1 поколением...есть еще 2 поколение...пока там только g216...есть еще 5 поколение - мультиварки...и есть нулевое поколение...самые древние...там пока только RK-M173S...судя по всему у вас именно нулевое поколение! а вы пытаетесь по 1 работать...там как раз разница в байтах по текущей температуре и методе включения! вам нужно в файле init.py найти строку:

SUPPORTED_DEVICES = {'RK-M173S':0, 'RK-G200S':1, 'RK-G201S':1, 'RK-G202S':1, 'RK-G210S':1, 'RK-G211S':1, 'RK-G212S':1, 'RK-M216S':2, 'RMC-M800S':5}


и добавить туда в начало ваше устройство: 'RK-M171S':0

**Comment by mavrikkk** [comment]
> Список устройств при добавлении интеграции появился

это хорошая новость, но какой ценой! вы отключили обнаружение и выбор физических устройств блютус...очень странно, что оно у вас не работает. что за железо? модуль блютус? что выдаст команда "hciconfig" набитая в консоли от рута, без рута?

**Comment by mavrikkk** [comment]
> чайник RK-M171S

RK-M171S такой чайник не заявлен у меня в поддержке! когда вы подключаете неподдерживаемое оборудование, то тип устройства ставится по умолчанию на мое поколение устройств...серия G200...я его назвал 1 поколением...есть еще 2 поколение...пока там только g216...есть еще 5 поколение - мультиварки...и есть нулевое поколение...самые древние...там пока только RK-M173S...судя по всему у вас именно нулевое поколение! а вы пытаетесь по 1 работать...там как раз разница в байтах по текущей температуре и методе включения! вам нужно в файле init.py найти строку:

SUPPORTED_DEVICES = {'RK-M173S':0, 'RK-G200S':1, 'RK-G201S':1, 'RK-G202S':1, 'RK-G210S':1, 'RK-G211S':1, 'RK-G212S':1, 'RK-M216S':2, 'RMC-M800S':5}

и добавить туда в начало ваше устройство: 'RK-M171S':0

**Comment by tayanov** [comment]
> > Считаю так же дополнить ридми
> 
> какая у вас конфигурация? в какой среде работает HA? вы сами ручками ставили в доккер? просто в hassio я не делал НИЧЕГО из вышеперечисленного...чтобы добавить в ридми, нужно понять, в каком именно случае что делать

У меня на основном инстансе были зависания с интеграцией.
Потому я тестово собрал малину  и поставил ее на кухне ближе к чайнику.
Конфигурачия такая: Rasbian последний, докер с HA без аддонов.
ОЛтключил встроенный блютус. Долго не мог сделать доступ к блютусу.
Делал доп. движения ... 
setcap для всех найденных bluepy-helper делал.
от юзера скрипт исполнялся. В ха заработало только после переключения NET_ADMIN в портейнере.

Сейчас могу сказать что ха на малине работает, как и интеграция с чайником.

Но думаю если вернуть блютус и интеграцию на x86 дле стоит дебиан и ха в докере, опять будут зависания. Свисток CSR4.0

**Comment by tayanov** [comment]
так же предложу заменить заглушку pass в configflow на вывод лога. Мне бы это помогло в отлавливании отсутствия прав на БТ. Рядовому ющеру интеграции коментирование try exept мне кажется не просто...

**Comment by mavrikkk** [comment]
> Рядовому ющеру интеграции коментирование try exept мне кажется не просто...

я бы согласился, но...поставить HA - это для обычного человека тоже нетривиальная задача...не говоря про выбор оборудования...а кто все это проделал по моему скромному мнению пару строчек поправить может )



> так же предложу заменить заглушку pass в configflow на вывод лога

но идея в принципе правильная...

**Comment by mavrikkk** [comment]
> Сейчас могу сказать что ха на малине работает, как и интеграция с чайником.
> 
> Но думаю если вернуть блютус и интеграцию на x86 дле стоит дебиан и ха в докере, опять будут зависания. Свисток CSR4.0

а вот и новые данные ))
на x86 даже не пробовал тестировать...что это? плохая работа блютус на x86? плохая оптимизация bluepy для x86? еще какие то чудеса?

**Comment by Seegak3** [comment]
> 
> это хорошая новость, но какой ценой! вы отключили обнаружение и выбор физических устройств блютус...очень странно, что оно у вас не работает. что за железо? модуль блютус? что выдаст команда "hciconfig" набитая в консоли от рута, без рута?

HA Supervised установлен с помощью скрипта на ТВ бокс Magicsee N6max с Armbian (встроенный блютус не работает), модуль блютус DEXP AT-BT403A ( Cambridge Silicon Radio)

Вывод команды "hciconfig" 
ha@n6max:~$ hciconfig
hci1:   Type: Primary  Bus: UART
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:4 acl:0 sco:0 commands:1 errors:0

hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:07  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:46386 acl:897 sco:0 events:2635 errors:0
        TX bytes:22303 acl:577 sco:0 commands:1001 errors:0

ha@n6max:~$ sudo hciconfig
hci1:   Type: Primary  Bus: UART
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:4 acl:0 sco:0 commands:1 errors:0

hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:07  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:46386 acl:897 sco:0 events:2635 errors:0
        TX bytes:22303 acl:577 sco:0 commands:1001 errors:0

**Comment by mavrikkk** [comment]
отлично, добавлю
