### ISSUE TITLE
Изменения в сущностях чайник

### ISSUE THREAD

**Issue by tayanov** [mavrikkk/ha_kettler#26]
Вот что висит в логах 
WaterHeaterDevice is deprecated, modify RedmondWaterHeater to extend WaterHeaterEntity
WaterHeaterDevice is deprecated, modify RedmondCooker to extend WaterHeaterEntity

Как я понимаю нужно подправить интеграцию под изменения?

**Comment by mavrikkk** [comment]
можете сами исправить...в инит исправить WaterHeaterDevice на WaterHeaterEntity
я чуть позже выложу
