### ISSUE TITLE
переустановка

### ISSUE THREAD

**Issue by Tombraider2006** [mavrikkk/ha_kettler#27]
Как всегда читаем инструкцию уже после того как все сломал. не могу удалить интеграцию. переустанавливал но в интеграциях так и висит kettler и не удаляется( 
писать надо что удалить надо перед обновлением,  а не после.. 
кстати заметил что при нажатии имени в hacs интеграциях выводит на чужую страницу github.com/mavrikk, а не github.com/mavrikkk и плиз залей архив старой версии чтоб можно было снести нормально.. гибну без горячего чая..

**Comment by profx5015** [comment]
[r4s_kettler 2.zip](https://github.com/mavrikkk/ha_kettler/files/4669171/r4s_kettler.2.zip)

При помощи этой интеграции удалил старую версию. Новая версия называется не r4s, а ready4sky.

**Comment by dPuhov** [comment]
После последнего обновления от 22го мая, не могу добавить чайник снова после удаления. В поле имя или адрес ничего не выводит, вписать вручную тоже никак.

**Comment by mavrikkk** [comment]
> Как всегда читаем инструкцию уже после того как все сломал

у меня получилось это сделать...пошагово не проведу, но где то в веб морде в настройках-интеграции есть возможность удалить интеграции...старые будут красным помечены



> выводит на чужую страницу github.com/mavrikk, а не github.com/mavrikkk

надо поправить ))

**Comment by mavrikkk** [comment]
> После последнего обновления от 22го мая, не могу добавить чайник снова после удаления. В поле имя или адрес ничего не выводит

значит у вас не работает поиск...предыдущая версия какая была? вручную вводили? что за конфигурация? если у вас до этого была версия, где вы вручную вводили, то почитайте один из закрытых issue https://github.com/mavrikkk/ha_kettler/issues/20  в других тоже было
