### ISSUE TITLE
skyiron c265s

### ISSUE THREAD

**Issue by Demonuka** [mavrikkk/ha_kettler#28]
У меня есть чайник RK-G210S и он прекрасно работает с Вашим плагином, спасибо! Но еще есть утюг skyiron c265s. Он нормально синхронизировался (определился в интеграции как RI-C265S). В родном приложении у него всего 1 функция - "Отключить". В этой интеграции отключается включением кнопки подсветки. Кнопка отщелкивает назад (видно ответ не такой, как ожидалось), но утюг реально отключается. При этом правильно отрабатывает статус (меняется с BOIL на OFF). Единственный минус - при отключении утюга от сети (а это его нормальное состояние), Home Assistant наглухо виснет. Собственно, тоже самое происходит и есть чайник из розетки вынуть. У меня HA вертится на HASSOS на RaspberyPI 4, так что вряд ли дело в железе. Видать синхронные попытки обмена слишком сильно нагружают HA. Нужны ассинхронные.

**Comment by mavrikkk** [comment]
> В этой интеграции отключается включением кнопки подсветки.

ну это просто совпадение...дело в том, что при включении подсветки у меня срабатывает отключение чайника...так что думаю, что именно отключение чайника равно отключение утюга...наверняка есть небольшие различия в статусе...подключить можно в общем



> Единственный минус - при отключении утюга от сети (а это его нормальное состояние), Home Assistant наглухо виснет. Собственно, тоже самое происходит и есть чайник из розетки вынуть.

надо протестировать...никогда не пробовал отключать чайник надолго...НО периодически снимаю его на несколько минут...учитывая период синхронизации в 30 сек, у меня все повиснуть должно было также...однако в логах только появляется сообщение о неудачных попытках коннекта (что логично)...



> вряд ли дело в железе.

ага, а вот в софте очень может быть )) здесь уже неоднократно всплывали разные ситуации и многие из них были так или иначе разрешены...почитайте все закрытые и открытые issue может поможет...



> Видать синхронные попытки обмена слишком сильно нагружают HA. Нужны ассинхронные.

возможно...однако
1. у самого HA есть блютус климат устройство написанное полностью синхронно...более того, моя предпоследняя версия основана на ней ))
2. я вроде как обернул все синхронные запросы в асинхронные вызовы (последняя версия)...правда никто разницы не заметил ))) в том числе и я...возможно не хватает знаний...
3. есть полностью асинхронная блютус библиотека bleak но кроме поиска устройств у меня ничего не работает ((( надо глубже копать либо найти готовый пример на ней...

**Comment by Demonuka** [comment]
Я неправильно выразился по поводу "наглухо виснет HA". На самом деле он не
виснет. И он действительно пишет в лог ошибки коннекта. И автоматизации
продолжают работать в нормальном режиме. Но вот интерфейс полностью
недоступен. Если устройство снова воткнуть в розетку, то все
восстанавливается. Но это действительно нужно тестить. Возможно реально
чисто у меня проблема такая.

пн, 25 мая 2020 г. в 07:19, mavrikkk <notifications@github.com>:

**Comment by mavrikkk** [comment]
да, подтверждаю...если убрать чайник с подставки надолго, то веб морда не открывается...при этом все работает...после установки чайника обратно, чайник сам подключается и интерфейс отвисает...
надо найти причину и искать решение

**Comment by mavrikkk** [comment]
> Собственно, тоже самое происходит и есть чайник из розетки вынуть

проверяйте на новой версии!
если проблем не будет, то добавим ваш утюг

**Comment by Demonuka** [comment]
Да, все отлично и с чайником и с утюгом! Спасибо большое! )
