### ISSUE TITLE
Периодически зависает Hassio

### ISSUE THREAD

**Issue by Aroxyson** [mavrikkk/ha_kettler#29]
Hassio периодически перестает отвечать при включенной интеграции чайника. При этом в логах следующее:

`2020-05-24 15:33:33 WARNING (MainThread) [custom_components.r4s_kettler] five attempts of modeUpdate failed`
`2020-05-24 15:33:33 WARNING (MainThread) [homeassistant.components.switch] Updating hdmi_cec switch took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:33:33 WARNING (MainThread) [homeassistant.components.light] Updating hyperion light took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:33:33 WARNING (MainThread) [homeassistant.components.light] Updating xiaomi_miio light took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:33:33 WARNING (MainThread) [homeassistant.components.fan] Updating xiaomi_miio fan took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:33:33 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miio switch took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:34:03 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:34:33 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:35:03 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of light.xiaomi_philips_smart_led_ball is taking over 10 seconds`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.humidifier is taking over 10 seconds`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.xiaomi_miio_switch is taking over 10 seconds`
`2020-05-24 15:35:31 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/ returned`
`2020-05-24 15:35:31 ERROR (MainThread) [homeassistant.components.met.weather] Retrying in 15 minutes`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.components.vacuum] Updating miio2 vacuum took longer than the scheduled update interval 0:00:20`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.components.light] Updating xiaomi_miio light took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.components.fan] Updating xiaomi_miio fan took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:35:31 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miio switch took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:35:33 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:36:03 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:36:33 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:37:03 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:37:14 WARNING (MainThread) [custom_components.r4s_kettler] five attempts of modeUpdate failed`
`2020-05-24 15:37:14 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.2792431728] Disconnected: Received non-Text message.`
`2020-05-24 15:37:14 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook db1679c3bc641b62ebff4c4ed2d70825f4e930d3880476303d583ec4938703c6`
`Traceback (most recent call last):`
`  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 78, in async_handle_webhook`
`    response = await webhook["handler"](hass, webhook_id, request)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook`
`    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run`
`    return await func(hass, config_entry, data)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 439, in webhook_update_sensor_states`
`    await hass.data[DOMAIN][DATA_STORE].async_save(safe)`
`  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in async_save`
`    await self._async_handle_write_data()`
`  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 210, in _async_handle_write_data`
`    self._write_data, self.path, data`
`concurrent.futures._base.CancelledError`
`2020-05-24 15:37:14 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook db1679c3bc641b62ebff4c4ed2d70825f4e930d3880476303d583ec4938703c6`
`Traceback (most recent call last):`
`  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 78, in async_handle_webhook`
`    response = await webhook["handler"](hass, webhook_id, request)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook`
`    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run`
`    return await func(hass, config_entry, data)`
`  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 439, in webhook_update_sensor_states`
`    await hass.data[DOMAIN][DATA_STORE].async_save(safe)`
`  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in async_save`
`    await self._async_handle_write_data()`
`  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 207, in _async_handle_write_data`
`    async with self._write_lock:`
`  File "/usr/local/lib/python3.7/asyncio/locks.py", line 92, in __aenter__`
`    await self.acquire()`
`  File "/usr/local/lib/python3.7/asyncio/locks.py", line 192, in acquire`
`    await fut`
`concurrent.futures._base.CancelledError`
`2020-05-24 15:37:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.vacuum is taking over 10 seconds`
`2020-05-24 15:37:14 WARNING (MainThread) [homeassistant.components.vacuum] Updating miio2 vacuum took longer than the scheduled update interval 0:00:20`
`2020-05-24 15:37:14 WARNING (MainThread) [homeassistant.components.switch] Updating hdmi_cec switch took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:37:14 WARNING (MainThread) [homeassistant.components.light] Updating hyperion light took longer than the scheduled update interval 0:00:30`
`2020-05-24 15:37:33 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
`2020-05-24 15:38:04 INFO (ThreadPoolExecutor-1_0) [pycec] Looking for new devices...`
**2020-05-24 15:38:25 WARNING (MainThread) [custom_components.r4s_kettler] five attempts of modeUpdate failed**
**2020-05-24 15:38:25 WARNING (MainThread) [homeassistant.components.light] Updating xiaomi_miio light took longer than the scheduled update interval 0:00:30**
**2020-05-24 15:38:25 WARNING (MainThread) [homeassistant.components.fan] Updating xiaomi_miio fan took longer than the scheduled update interval 0:00:30**
**2020-05-24 15:38:25 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_miio switch took longer than the scheduled update interval 0:00:30**

То есть появляются ошибки обновления ВСЕХ (но это неточно, пылесос не всегда в этой компании) сущностей. Так же проскакивает ошибка обновления статуса чайника. Характер зависаний таков: HA перестает отвечать в веб морде, проходит минуты 3-4, он отмирает, работает это все минуты 3-4 и заново. Видимо в момент попытки обновления (синхронного?) ХА умирает. После отключения интеграция проблема уходит. Не знаю как это все связано, но как есть. 

Пока что возвращаюсь к старой версии.

Raspberry Pi 4
Версия HA (Hassio) - 0.109.6
Чайник Kettle RK-G210S

**Comment by mavrikkk** [comment]
судя по вашему логу, у вас и есть старая версия...новая ready4sky называется, а не r4s_kettler

**Comment by mavrikkk** [comment]
а вообще, плодить одинаковые issue не нужно...
