### ISSUE TITLE
некорректно появляется чайник RK-G210S 

### ISSUE THREAD

**Issue by Suppv** [mavrikkk/ha_kettler#30]
после установки интеграции ready4sky и настройки ее в интеграции появляется единственный сенсор - статус чайника.
в логах ошибка Unable to prepare setup for platform ready4sky.light   ready4sky.water_heater.
в чем дело?

**Comment by Suppv** [comment]
вот такое в логах:
Unable to prepare setup for platform ready4sky.light: Platform not found (cannot import name 'LightEntity' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)).
Unable to prepare setup for platform ready4sky.water_heater: Platform not found (cannot import name 'WaterHeaterEntity' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)).

**Comment by mavrikkk** [comment]
обновите home assistant...
в новой версии они удалили некоторые сущности и добавили другие...я переделал под это.
