### ISSUE TITLE
Install into home-assistant core (Установка в home-assistant core)

### ISSUE THREAD

**Issue by SANiMirrorOfLight** [mavrikkk/ha_kettler#34]
Hello, could you please give some recommendations for using this component with home-assistam core?

I've already installed `pybluez` and `bluepy` components but the integration does not see my RK-G213S kettle. One of the first versions of your component was working fine enough with my kettle previously.

(Добрый день, не могли бы вы поделиться рекомендациями по настройке вашего компонента для работы в home-assistant core? 

Более ранние варианты компонента работали с моим чайником, а этот все не удается завести. Я установил `pybluez` and `bluepy` но чайника нет в списке устройств. Чайник RK-G213S)

**Comment by SANiMirrorOfLight** [comment]
It seems like I managed to add the kettle by doing the following:

`sudo setcap 'cap_net_raw,cap_net_admin+eip' <PATH>/bluepy-helper`

`<PATH>` in my case is `/srv/homeassistant/lib/python3.7/site-packages/bluepy`

**Comment by SANiMirrorOfLight** [comment]
Anyway, I cannot turn on the kettle.
But I could do this with the previous version of the ha_kettler component.

**Comment by mavrikkk** [comment]
Hi.
1. try the same password as in the previous version.
2. send me your HA logs

**Comment by SANiMirrorOfLight** [comment]
> Hi.
> 
> 1. try the same password as in the previous version.
> 2. send me your HA logs

I reconnected my kettle.

It seems like I may turn on the kettle but it performs with some latency.

Here is what was added to the log file:

> 2020-06-23 16:19:37 ERROR (SyncWorker_19) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 16:19:37 ERROR (SyncWorker_19) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 16:19:37 ERROR (SyncWorker_19) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 16:19:37 ERROR (SyncWorker_19) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 16:19:37 ERROR (SyncWorker_19) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 16:19:37 WARNING (SyncWorker_19) [custom_components.ready4sky] five attempts of modeUpdate failed

Another try of turning on (the kettle was turned on after some seconds):

> 2020-06-23 17:04:20 ERROR (SyncWorker_16) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 17:04:20 ERROR (SyncWorker_16) [custom_components.ready4sky] unable to connect to device
> 2020-06-23 17:04:24 WARNING (SyncWorker_16) [custom_components.ready4sky] five attempts of modeUpdate failed

**Comment by SANiMirrorOfLight** [comment]
It seems like the integration has some trouble with connecting to the kettle all the time.
The home-assistant log is full of the following messages:

> 2020-06-26 10:57:11 WARNING (SyncWorker_11) [custom_components.ready4sky] five attempts of modeUpdate failed
> 2020-06-26 10:58:11 ERROR (SyncWorker_6) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:58:11 ERROR (SyncWorker_6) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:58:11 ERROR (SyncWorker_6) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:58:11 ERROR (SyncWorker_6) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:58:12 ERROR (SyncWorker_6) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:58:12 WARNING (SyncWorker_6) [custom_components.ready4sky] five attempts of modeUpdate failed
> 2020-06-26 10:58:24 ERROR (SyncWorker_16) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:12 ERROR (SyncWorker_12) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:12 ERROR (SyncWorker_12) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:12 ERROR (SyncWorker_12) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:12 ERROR (SyncWorker_12) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:13 ERROR (SyncWorker_12) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 10:59:13 WARNING (SyncWorker_12) [custom_components.ready4sky] five attempts of modeUpdate failed
> 2020-06-26 11:00:13 ERROR (SyncWorker_15) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:00:13 ERROR (SyncWorker_15) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:00:13 ERROR (SyncWorker_15) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:00:13 ERROR (SyncWorker_15) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:00:14 ERROR (SyncWorker_15) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:00:14 WARNING (SyncWorker_15) [custom_components.ready4sky] five attempts of modeUpdate failed
> 2020-06-26 11:01:14 ERROR (SyncWorker_17) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:01:14 ERROR (SyncWorker_17) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:01:14 ERROR (SyncWorker_17) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:01:14 ERROR (SyncWorker_17) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:01:15 ERROR (SyncWorker_17) [custom_components.ready4sky] unable to connect to device
> 2020-06-26 11:01:15 WARNING (SyncWorker_17) [custom_components.ready4sky] five attempts of modeUpdate failed

**Comment by mavrikkk** [comment]
it is very strangely.
there is no difference between first connect and update methods. if the first connect works update must work too
and update method has no binding with turn on or turn off methods. why do you get update error when you try to turn on or turn off the device? i dont understand for a while. maybe you set too little time interval to update?

**Comment by SANiMirrorOfLight** [comment]
I have tones of such log messages so they do not relate to turning on/off commands. It seems like they related to the update method.

I set 60 seconds for the update interval.

**Comment by mavrikkk** [comment]
hmm...current log didnt help.
clear your log...restart HA and find first few error messages in LOG related to kettle. maybe the answer is there.
