### ISSUE TITLE
Integration creates two sets of entities

### ISSUE THREAD

**Issue by KhomichMO** [mavrikkk/ha_kettler#36]
Kettle: G200S

After each HA reload new set of entities are created: first "RK-G200S", after the next reload - "redmond sky" (RK-G200S is deactivated), then back to RK-G200S and so on.

![image](https://user-images.githubusercontent.com/11392034/86527565-4c3da100-beca-11ea-80b8-6704c14497c4.png)

**Comment by mavrikkk** [comment]
Hi
I cannot confirm your bug.
how to get this bug?
i tried to completely delete the integration, then reboot HA, then install it again, then several reboots to check the bug...and nothing. I have only "RK-G200S" after every reboot. "redmond sky" can appear only if "findType" function doesnt work.

**Comment by mavrikkk** [comment]
here is the better syntax:
https://pastebin.com/A0LGHiBh

**Comment by mavrikkk** [comment]
then catch your logs

**Comment by KhomichMO** [comment]
Using your code caught this:

dev_name is None
8:43:07 PM – ready4sky (ERROR)

**Comment by mavrikkk** [comment]
it means, that my integretion cant find your device in 2 sec. try to increase the counter to, may be, 5 sec.
ble_devices = {device.addr:str(device.getValueText(9)) for device in scanner.scan(**2.0**)}

**Comment by mavrikkk** [comment]
generally, pay attention to your bluetooth hardware (RPI integrated ble is very bad) and the distance between HA and kettle

**Comment by KhomichMO** [comment]
Seems to work with 5 secs, thanks.
