### ISSUE TITLE
Пароль устройства

### ISSUE THREAD

**Issue by uPagge** [mavrikkk/ha_kettler#38]
Где взять пароль?

**Comment by uPagge** [comment]
Разобрался, видимо можно любой набрать?

**Comment by aperedreev** [comment]
Всё верно)

**Comment by uPagge** [comment]
> Всё верно)

Смог добавить чайник, но ничего не могу с ним сделать, даже запустить

![изображение](https://user-images.githubusercontent.com/40397740/89109807-37164c80-d44d-11ea-99d9-a006ef0ca76e.png)

**Comment by aperedreev** [comment]
> > Всё верно)
> 
> 
> 
> Смог добавить чайник, но ничего не могу с ним сделать, даже запустить
> 
> 
> 
> ![изображение](https://user-images.githubusercontent.com/40397740/89109807-37164c80-d44d-11ea-99d9-a006ef0ca76e.png)
> 
> 

Попробуй этот пароль: 

ab64e6f700f75c65

**Comment by uPagge** [comment]
> ab64e6f700f75c65

Пароль помог, но частично.

Появилась возможность управлять подсветкой (включать и выключать синий свет)
Отображает температуру
Показывает статус (BOLL, OFF)

Но влючать чайник все еще нельзя, нет даже такого варианта((

**Comment by uPagge** [comment]
![изображение](https://user-images.githubusercontent.com/40397740/89738700-4d428f00-da83-11ea-9b8e-015dbf5b8888.png)

нашел как включать, спрятано в карточке устройства, было бы неплохо сделать отдельный переключатель, как у светильника :) 

Спасибо за подсказку с паролем))

**Comment by uPagge** [comment]
хмм, кажется я поторопился и этот переключатель это подсветка :(

**Comment by uPagge** [comment]
Кажется я нашел видос на ютубе, где есть как раз то что я хочу

`- platform: template
    switches:
      kettle_work:
        value_template: "{{ is_state ('water_heater.g200s', 'electric') }}"
        turn_on:
          service: water_heater.set_operation_mode
          data:
            entity_id: water_heater.g200s
            operation_mode: electric
        turn_off:
          service: water_heater.set_operation_mode
          data:
            entity_id: water_heater.g200s
            operation_mode: 'off'
`

**Comment by uPagge** [comment]
Правда переключатель почему-то только включается, но не сохраняет статус чайника, и поэтому им нельзя выключить, только включить

**Comment by aperedreev** [comment]
> ![изображение](https://user-images.githubusercontent.com/40397740/89738700-4d428f00-da83-11ea-9b8e-015dbf5b8888.png)
> 
> 
> 
> нашел как включать, спрятано в карточке устройства, было бы неплохо сделать отдельный переключатель, как у светильника :) 
> 
> 
> 
> Спасибо за подсказку с паролем))

Не за что) Чайник включается при выставлении температуры же. Переключатель в видео он добавлял для HomeKit вроде. Я в HomeKit прокидывал через Node-Red. Через родную интеграцию HA он не передаёт текущую температуру.
