### ISSUE TITLE
Критичная ошибка | hacs

### ISSUE THREAD

**Issue by uPagge** [mavrikkk/ha_kettler#40]
Путем эксперементов обнаружил следующую проблему.

Я успешно добавил чайник, но столкнулся со следующим багом.

Если связи с чайником нет, а HA перезапускается, то hacs не стартует, при этом могут отвалиться некоторые аддоны, такие как (file editor, log view и прочие), HA не стартует до конца, то есть пишет что он еще не запустился полностью, при этом не срабатывают автоматизации настроенные на тригер запуска HA. В логе я как раз нашел запись, про то что не может стартануть именно эта интеграция. При этом нет возможности перезагрузить HA из интерфейса, все виснит намертво, вкладка UI, на которой размещен чайник перестает отображаться.

При этом, если попробовать удалить интеграцию из hacs, то полностью сносится папка custom_components

Вообщем видимо не хватает какого-то обработчика, чтобы если с устройством нет связи, то пропустить запуск интеграции, точто не знаю как там все устроено, но он точно долбится в интеграцию пытаясь ее запустить (скрин). Если вставить чайник в розетку, то HA запускается сразу до конца, но сама интеграция не работает

Перезагружал множество раз.

![изображение](https://user-images.githubusercontent.com/40397740/89814780-5c414400-db4c-11ea-90d0-1cefdf101d39.png)

![изображение](https://user-images.githubusercontent.com/40397740/89815238-1df85480-db4d-11ea-9577-5c8c12db5c6f.png)

**Comment by aperedreev** [comment]
А на чем Homeassistant крутится? У меня вообще тут начались переодические зависания - просто становятся недоступны устройства, raspberry моргает светодиодом, на ощупь теплее чем при обычной работе. После перезагрузки все запускалось заново, но после последнего зависания не запустился HA в докере, MQTT и Node-Red запускаются нормально. Логи пока не изучал, некогда) Raspberry Pi Zero.

**Comment by uPagge** [comment]
@aperedreev у меня PI 4 b+, запущено все это дело в докер контейнерах, на raspbian lite. Но кроме HA ничего там не крутится пока что

**Comment by aperedreev** [comment]
> @aperedreev у меня PI 4 b+, запущено все это дело в докер контейнерах, на raspbian lite. Но кроме HA ничего там не крутится пока что
> 
> 

А если удалить свитч из конфига? Нет связи с чайником - когда он не подставке? Если он включён, то все норм?

**Comment by aperedreev** [comment]
Починю хомассистант - попробую у себя перезапуститься с выключенным чайником.

**Comment by uPagge** [comment]
@aperedreev не удалял, из конфига это из UI или из интеграции?

Когда чайник включен все норм, когда выключен из розетки, то HA не загружается.

**Comment by aperedreev** [comment]
@uPagge Не так прочитал, на скрине в логе он ругается на свитч, я сначала подумал это свитч для чайника(переключатель из видео), а там xiaomi_miio. Вот он смущает, я насколько понимаю, красные ошибки ERROR не дают грузится ХА, а у r4s желтый WARNING - он не должен препятствовать загрузке. Конфиг я имел в виду файл configuration.yaml

**Comment by uPagge** [comment]
Не, ERROR вообще никак не мешает на удивление :D Все работает нормально с ним

Из конфига не удалял, но у меня там и нет ничего, я добавлял через интерфейс
