### ISSUE TITLE
Не подключает чайник 

### ISSUE THREAD

**Issue by Vooovan** [mavrikkk/ha_kettler#42]
Установил репозиторий через hacs, добавил интеграцию, в ней выбрал чайник (находит по блютуз), все настройки 
чайник просто не находит. некая непонятная ошибка
<img width="588" alt="Снимок экрана 2020-09-23 в 15 03 23" src="https://user-images.githubusercontent.com/67726392/94014033-a5bfb880-fdb3-11ea-9c28-5ec0890b47b3.png">
<img width="489" alt="Снимок экрана 2020-09-23 в 15 42 22" src="https://user-images.githubusercontent.com/67726392/94014055-ad7f5d00-fdb3-11ea-8e2f-b0eb23720b64.png">
<img width="603" alt="Снимок экрана 2020-09-23 в 15 44 42" src="https://user-images.githubusercontent.com/67726392/94014112-c25bf080-fdb3-11ea-9c60-f3268a3ab348.png">
повторно нажать подтвердить не удается.
вот и вопрос что делать
<img width="893" alt="Снимок экрана 2020-09-23 в 15 46 39" src="https://user-images.githubusercontent.com/67726392/94014395-2383c400-fdb4-11ea-832a-26b1b79db7b5.png">

**Comment by mavrikkk** [comment]
У вас не происходит коннект... ошибка вот на этой строчке:

self._conn = btle.Peripheral(deviceAddr=self._mac, addrType=btle.ADDR_TYPE_RANDOM)

bluepy работает только под рутом...пролистайте здесь закрытые issues. Там в нескольких уже есть решение вашей проблемы.

**Comment by Vooovan** [comment]
Ушел думать. Спасибо.

**Comment by mavrikkk** [comment]
по неактивности закрываю
