### ISSUE TITLE
Адаптация rk-g240s

### ISSUE THREAD

**Issue by ruslankuchkarov** [mavrikkk/ha_kettler#43]
Добрый день! Скажите пожалуйста, с чего нужно начать для того, чтобы адаптироваться под g240s? Перехватил все, чем обмениваются между собой смартфон и чайник, но что-то не могу ни авторизацию там найти (запрос 0100 на хендл 0x000c), ни чего-либо, что похоже на включение/выключение чайника...

**Comment by mavrikkk** [comment]
Добрый день!
Начали вы правильно.
Скиньте пример обмена телефона с чайником.

**Comment by ruslankuchkarov** [comment]
У меня есть лог, который записался во время общения телефона и чайника, но он какой-то общий. Давайте я скину, но кажется он какой-то избыточный.
[hci_snoop_2020_10_04_23_42_52.zip](https://github.com/mavrikkk/ha_kettler/files/5323654/hci_snoop_2020_10_04_23_42_52.zip)

**Comment by mavrikkk** [comment]
лучше бы на тлф (андроид) включили бы отладку блютус...он в простом тхт пишет  лог в корень сторейджа

**Comment by ruslankuchkarov** [comment]
А это как раз с телефона (OnePlus 5T) лог с таким расширением сохраняется. Скажите, а вы же в whireshark разбираете логи? Если да, то подскажите пожалуйста, какие фильтры применяете? Я бы тогда смог прям отфильтрованный лог скинуть. Пытался фильтрануть по хендлу 0x000c (btatt.handle == 0x000c) и нашел 2 такие записи:
0000   02 02 20 0a 00 06 00 04 00 05 01 0c 00 02
0000   02 03 20 0a 00 06 00 04 00 05 01 0c 00 02

**Comment by ruslankuchkarov** [comment]
Я зря вас мучал...) Я просто пароль некорректный вводил при добавлении интеграции... В общем всё и так работает. Спасибо вам за вашу работу)

**Comment by mavrikkk** [comment]
хорошая новость. Вы добавляли свой чайник в список? или само все заработало, без правки кода?

**Comment by mavrikkk** [comment]
ну а так...фильтровать нужно по источнику и приемнику )) в источник ставишь тлф и чайник...и в приемник тлф и чайник...и получаешь только полезный трафик конкретно между 2 этими устройствами

**Comment by ruslankuchkarov** [comment]
> хорошая новость. Вы добавляли свой чайник в список? или само все заработало, без правки кода?

Само заработало) единственное - цветовой палитры подсветки нет) это хоть и прикольно, но в принципе не так уж и важно)

**Comment by mavrikkk** [comment]
отлично!
