### ISSUE TITLE
Конвектор Redmond SkyHeat RCH-4529S.

### ISSUE THREAD

**Issue by evteevalex** [mavrikkk/ha_kettler#44]
Здравствуйте,получится добавить Конвектор Redmond SkyHeat RCH-4529S?
[btsnoop_hci.zip](https://github.com/mavrikkk/ha_kettler/files/5353791/btsnoop_hci.zip)

**Comment by mavrikkk** [comment]
наверняка можно...
а что он умеет?
1. включаться
2. выключаться
...
что то еще? поддерживать температуру? показывать текущую температуру?

нужны мак адреса вашего тлф и конвектора, чтобы отсеять в логе полезный трафик

**Comment by mavrikkk** [comment]
1. мак адреса сам нашел.
2. команда статуса такая же
думаю многие команды совпадут, НО специфические параметры и команды могут быть...поэтому нужен список того, что умеет конвертор...
после этого буду у вас запрашивать специфичные логи.

**Comment by evteevalex** [comment]
Умеет включаться и выключаться.Блокировка включения с кнопки (защита от детей) и всё.Температуру он не поддерживает и не знает её.

**Comment by evteevalex** [comment]
Ваша интеграция видит устройство,подключается,видит состояние (off и boil).Есть переключатель,если включить,он включит конвектор и выключит через пару секунд.

**Comment by mavrikkk** [comment]
круто! значит почти все совпало!
тогда нужно сделать так:
отключить все блютус устройства от тлф кроме конвертора. включить запись лога блютус...зайти в приложение...

1. включить конвертор...подождать 10 сек...выключить конвертор...подождать 10 сек...
2. повторить пункт 1 еще 2 раза...выйти из приложения, отключить блютус, остановить запись лога....скинуть лог сюда

итого у меня будет последовательная запись 3 событий...найду, думаю

**Comment by mavrikkk** [comment]
и вопрос: блокировка включения с кнопки - это функция в приложении? чтоб дети физически ничего не щелкали? если да, тогда мне нужен будет отдельный лог для этой функции, если она вам нужна...все тоже самое, что и в предыдущем сообщении проделать, только включать и выключать эту функцию и все...лог отдельный, с тем не путать

**Comment by evteevalex** [comment]
Включение и выключение
[btsnoop_hci.zip](https://github.com/mavrikkk/ha_kettler/files/5354648/btsnoop_hci.zip)

**Comment by evteevalex** [comment]
Включение блокировки.
[btsnoop_hci.zip](https://github.com/mavrikkk/ha_kettler/files/5354672/btsnoop_hci.zip)

**Comment by mavrikkk** [comment]
а как это выглядит в HomeAssistant сейчас?

**Comment by evteevalex** [comment]
Подождите обновлю

**Comment by evteevalex** [comment]
Включил через ha,конвектор включен.

![2020-10-09_19-07-21](https://user-images.githubusercontent.com/52439342/95581260-e893b880-0a62-11eb-8cf4-c0545542597c.png)

**Comment by mavrikkk** [comment]
как я вижу, определяется в системе как RFS-HPL001 а не RCH-4529S ?
это важно для вода

**Comment by evteevalex** [comment]
Я название не менял

**Comment by mavrikkk** [comment]
попробуйте обновить компонент и проверить
в первом приближении сделал включение и выключение

**Comment by evteevalex** [comment]
На переключатель срабатывает с опозданием (секунд 20)
В HA появились ошибки
2020-10-09 20:00:15 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry d6:a0:f6:61:0f:a1 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 316, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 78, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by mavrikkk** [comment]
настройки - интеграции - ready4sky - три точки - удалить.

перезагрузить HA

обновить интеграцию ready4sky (есть вероятность, что 1 файл старый остался )

настройки - интеграции - добавить - ready4sky.
настраиваете как обычно.
пробуете, пишите отзыв.
продолжим на следующей неделе, если не заработает

**Comment by mavrikkk** [comment]
заодно скиньте фото, как сейчас выглядит в HA

**Comment by evteevalex** [comment]
В Hacs переустановил.
Удалил интеграцию и настроил.
![2020-10-09_21-47-00](https://user-images.githubusercontent.com/52439342/95597645-197ee800-0a79-11eb-9374-0d664117a802.png)

**Comment by evteevalex** [comment]
Завтра полностью удалю, файлы в ручную,и настрою.

**Comment by mavrikkk** [comment]
у вас он не так должен выглядеть...значит не определился тип...значит, что то не то с именем...не зря я спрашивал...как вы видите имя, когда на этапе подключения сканируется окружение? вот это имя мне нужно

**Comment by evteevalex** [comment]
![2020-10-10_07-45-47](https://user-images.githubusercontent.com/52439342/95642912-ecacee00-0ad5-11eb-8e5f-81ce977526c7.png)

**Comment by evteevalex** [comment]
Удалил все файлы,и настроил заново.
![2020-10-10_08-53-46](https://user-images.githubusercontent.com/52439342/95642974-575e2980-0ad6-11eb-9009-e72780300516.png)

**Comment by mavrikkk** [comment]
у вас он вообще не так должен выглядеть... сейчас у вас не тот тип устройства. должен быть сенсор и свитч... ни света, ни чайника быть не должно.
1. вы точно обновили модуль? 
2. не скрином, а текстом пришлите имя...в момент когда у вас поиск устройства, прям скопируйте строку и пришлите сюда, может я в имени 0 и о перепутал... хотя они вроде не похожи...

**Comment by evteevalex** [comment]
1.Удалил папку custom_components - ready4sky.Скачал с githab'а и установил.
2.Скопировал при сопряжении
RFS-HPL001,d6:a0:f6:61:0f:a1

**Comment by mavrikkk** [comment]
попробуй поставь заново...вставил в код имя, прям скопипастив с сообщения выше.
У тебя после подключения должны быть только свич и сенсор...никаких water heater и light

**Comment by mavrikkk** [comment]
вставил в код скопированное имя с предыдущего коммента...пробуйте...
у вас в любом случае должны быть только switch и sensor...никакого water_heater и light быть не должно!

**Comment by evteevalex** [comment]
Извините, попробую только через 6 часов,сейчас на работе.

**Comment by evteevalex** [comment]
Вот так должно быть?

 
![2020-10-12_19-31-59](https://user-images.githubusercontent.com/52439342/95746899-ba5fe400-0cc1-11eb-841e-7f6519bfdae0.png)

**Comment by evteevalex** [comment]
Переключатель работает,состояние показывает.Если переключить кнопкой с конвектора в HA состояние переключателя и сенсора меняет.

**Comment by mavrikkk** [comment]
1. поздравляю. все работает!
2. насчет коннекта - я никак повлиять не могу...сто раз тут обсуждалось: если втроенный в малинку блютус - меняй на свисток, следи за расстоянием между приемником и передатчиком...
3. блокировка от детей нужна?

**Comment by evteevalex** [comment]
1.Вам спасибо
2.Свисток на Xpenology.Растояние 50см.
3.Мне не нужен.

**Comment by mavrikkk** [comment]
2. да, у меня лично и у многих тут возникала такая же проблема. я в итоге перешел на малинку. Здесь тоже ссылки уже давал на этот счет: где-то читал, что блютус в докере на синолоджи работает весьма так себе (не говоря уже про неофициальный xpenology). Плюс, может сам модуль. В общем, надо экспериментировать. Если есть возможность - попробуйте на другом железе. Кто то пошел другим путем: поставил шлюз отдельный и доволен: 
https://github.com/mavrikkk/ha_kettler/issues/24
