### ISSUE TITLE
Добавить чайник RK-M216S в ваш проект.

### ISSUE THREAD

**Issue by acckii** [mavrikkk/ha_kettler#45]
Можно ли добавить чайник RK-M216S в ваш проект? Чайник достаточно популярный. Последняя модель. Почти год на рынке. Хочется его увидеть в вашем компоненте.

**Comment by 3AXAPOB** [comment]
Давно добавлено и работает.

**Comment by mavrikkk** [comment]
данный чайник есть в списке поддерживаемых...если что то не работает - конкретизируйте

**Comment by acckii** [comment]
> данный чайник есть в списке поддерживаемых...если что то не работает - конкретизируйте

В описании проекта это не указано. Либо я не увидел.

**Comment by vorlocsev** [comment]
> данный чайник есть в списке поддерживаемых...если что то не работает - конкретизируйте

доступны только сенсоры состояния и температуры, управление не действует
