### ISSUE TITLE
Не удаётся установить интеграцию

### ISSUE THREAD

**Issue by acckii** [mavrikkk/ha_kettler#46]
Не могу установить интеграцию. Поле MAC адрес не активно. При нажатии на кнопку подтвердить, выходит сообщение User input malformed. Подскажите, что я делаю не так.
![image](https://user-images.githubusercontent.com/60110563/95768968-cd71b480-0cbf-11eb-9727-b32692216152.png)

**Comment by mavrikkk** [comment]
что в логе?
сходу могу предположить, что не отрабатывает скан устройств (потому и пустой список)
Вы внимательно все читали? блютусу нужен рут для нормальной работы. Здесь уже многократно в закрытых issues обсуждалось, что нужно делать.

**Comment by acckii** [comment]
У меня Synology, на нем Docker в котором HASS.io. Есть ли решение, можете
ссылкой поделиться?

чт, 15 окт. 2020 г., 11:15 mavrikkk <notifications@github.com>:

**Comment by mavrikkk** [comment]
для начала - лог!
Отключаете интеграцию...перезагружаетесь...включаете интеграцию...смотрите лог...шлете сюда

**Comment by mavrikkk** [comment]
по умолчанию блютус не прокидывается в докер синолоджи. решение на офф сайте:
https://www.home-assistant.io/docs/installation/docker/
пункт SYNOLOGY NAS
там написано про Z-Wave USB stick, но это неважно в принципе. у вас BLE USB stick.

**Comment by acckii** [comment]
Вечером попрбую

чт, 15 окт. 2020 г., 11:58 mavrikkk <notifications@github.com>:

**Comment by ruslankuchkarov** [comment]
Обновил сегодня HassOS и точно так же стало(

**Comment by acckii** [comment]
Права root есть. В логах чисто. Нет даже упоминаний при запуске интеграции.
Может я не правильно логи снимаю?

пн, 19 окт. 2020 г., 14:57 ruslankuchkarov <notifications@github.com>:

**Comment by mavrikkk** [comment]
Home Assistant 0.116.4

supervisor 247

все работает

![image](https://user-images.githubusercontent.com/42514734/96449452-e92c0c00-1225-11eb-93a7-3f4bff3e651b.png)

**Comment by mavrikkk** [comment]
@ruslankuchkarov как это вообще могло случиться при обновлении? у вас уже есть настроенное устройство, как вы попали на экран установки?
Тоже самое у вас быть не может, раз у вас уже работало!
HA у меня последний, как и sypervisor. Интеграция работает и видит устройства!

**Comment by mavrikkk** [comment]
@ruslankuchkarov @acckii 
На данном этапе выполняются всего 2 команды:
1. hciconfig - для получения списка физических устройств блютус в вашем сервере. Если ничего не обнаружено, то система будет считать что это устройство 'hci0'
2. scanner.scan(3.0) - сканирование эфира в течение 3 сек на наличие устройств поблизости с того интерфейса, который получен в пункте 1.

соответственно, у вас в списке выбора устройств может быть если либо нет физически блютуса у вас...либо не сработал скан (работает только с правами рут, где то надо разрешить работу с блютус без рута...)

**Comment by ruslankuchkarov** [comment]
Сейчас опишу, как всё было и как я починил)
В супервизоре увидел обнову HassOS. У меня стояла 4.13, он предложил обновиться до 4.14. Обновился и после этого на lovelace панели у меня перестал отображаться статус чайника и кнопка его включения стала серой. Ну думаю, давай ка переинтегрирую... Так я попал на этот экран настройки)
Откат на предыдущую версию помог. Для этого в ssh говорим: ha os update --version 4.13

**Comment by mavrikkk** [comment]
@ruslankuchkarov к сожалению, у меня не HassOS, а HassIO. это ручная установка супервайзд версии homeassistant на raspberry. Проверил: все работает на самой последней версии.

В вашем случае возможны варианты:

1. HassOS при обновлении специально проводит некие манипуляции, например, возвращает права на блютус. (маловероятно, тогда откат на предыдущую вряд ли помог бы).

2. HassOS при обновлении случайно сломал что-то (да, такое тоже бывает, сталкивался несколько раз).

3. HassOS при обновлении специально сделал некие шаги, которые привели к поломке интеграции. Тогда это навсегда. 

Первый и второй варианты решимы вами без моего участия, притом первый еще и маловероятен в принципе.
Третий вариант самый плохой. Вам нужно узнать, что и как изменилось и тогда я попробую подогнать интеграцию под требования. Это нужно либо читать чейнджлог HassOS, либо смотреть, что в логах (как homeassistant, так и supervisor и тд).

**Comment by ruslankuchkarov** [comment]
Спасибо за такой развернутый ответ!
Нашёл ишью в репе HassOS:
https://github.com/home-assistant/operating-system/issues/910
Похоже это оно. Видимо, сами починят в следующем релизе.
