### ISSUE TITLE
ошибка в последнем обновлении

### ISSUE THREAD

**Issue by V-A-S** [mavrikkk/ha_kettler#47]
интеграция установлена через hacs, до последнего обновления ошибок не было 
`2020-10-15 10:50:52 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration ready4sky: No module named 'r4sconst'`

**Comment by mavrikkk** [comment]
к сожалению, последние 2 версии пишу вслепую ))
чайник после 5 лет работы помер смертью храбрых...тестировать нечего )
я пытался названия моделей вывести в отдельный файл r4sconst. Видимо что-то пошло не так. Интересно, что обновлению уже несколько дней. Либо остальные не обновляются, либо проблема только у вас. Посмотрите у вас в папке с модулем вообще есть этот файл r4sconst.py?

**Comment by V-A-S** [comment]
да, есть. я ревертнул изменения и интеграция заработала

**Comment by mavrikkk** [comment]
ревертнул? старую версию поставили?

**Comment by mavrikkk** [comment]
исправил. точку в синтаксисе забыл поставить. Обновитесь еще раз и проверьте!

**Comment by V-A-S** [comment]
да, обновление помогло. спасибо! теперь интеграция завелась. 

но моему RK-G214S от этого не легче, его в списке поддерживаемых не видно. но это уже к изначальной проблеме отношения не имеет

**Comment by mavrikkk** [comment]
нет в списке - это не страшно...
интеграция работает в текущем варианте с вашим чайником RK-G214S?

**Comment by mavrikkk** [comment]
если работает частично, то опишите, что работает?
например, показывается ли статус при включении чайника вручную? (с учетом задержки, которую вы выставили при подключении). может работает включение? или только выключение? или все работает? или все не работает?

**Comment by V-A-S** [comment]
у мня картина такая же, как в https://github.com/mavrikkk/ha_kettler/issues/46 
права через setcap поправил (на bluepy-helper и даже на сам питон), но результат тот же
похоже проблема в самом блютусе, он как-то странно работает. точнее то работает и дискаверит новые устройства (однако чайник не види), то наглухо засыпает и home assistant не может до него достучаться. ну и донгл сам по себе старый, не помню какую из версий блютус он поддерживает. тоже, наверное, может быть причиной

**Comment by mavrikkk** [comment]
ясно.
блютус должен быть версии не ниже 4 с поддержкой BLE, иначе он и не увтидит чайника
