### ISSUE TITLE
Отсутствует интеграция

### ISSUE THREAD

**Issue by jkcufa** [mavrikkk/ha_kettler#48]
Установил репозиторий через HACS, перезагрузил, но в настройках в интеграции нет компонента redmond.
Проверил файлы в папке custom components, всё на месте.
Home Assistant 0.116.4
Установлен образ с сайта HA. 
![2020-10-17](https://user-images.githubusercontent.com/60481418/96349661-57f45280-10ca-11eb-96ad-1db1ed703857.png)
![2020-10-17 (1)](https://user-images.githubusercontent.com/60481418/96349671-76f2e480-10ca-11eb-872c-f2aa5efb0e91.png)

**Comment by jkcufa** [comment]
Home Assistant 0.116.4

**Comment by mavrikkk** [comment]
имя ready4sky
