### ISSUE TITLE
RK-M216S

### ISSUE THREAD

**Issue by ResidentYAR** [mavrikkk/ha_kettler#52]
добрый день, не определяется модель интеграцией, пишет просто ReadyForSky, так же было с чайником G200S. Самый главный вопрос как можно одним нажатием и интерфейсе HA либо сторонней кнопкой нагреть до определенной температуры? а не как сейчас заходить и выставлять нужную температуру. Понимаю что нужна автоматизация но сам не могу допереть что прописать. Спасибо.

**Comment by mavrikkk** [comment]
вам нужно создать скрипт (сценарий). тип действия: вызов службы. служба: water_heater.set_temperature.  данные: нужная температура
сколько режимов нужно, столько и скриптов.

**Comment by dmburmagin** [comment]
Куда то пропала интеграция в последней версии HA. На сайте в списке интеграций тоже нет. Хотел сейчас установить. 
![image](https://user-images.githubusercontent.com/56762181/100127603-57e92e80-2e90-11eb-8cf5-69e1bd938e3c.png)
