### ISSUE TITLE
2 устройства сразу

### ISSUE THREAD

**Issue by agospher4eg** [mavrikkk/ha_kettler#54]
![Screenshot from 2020-11-27 12-50-20](https://user-images.githubusercontent.com/32064588/100435708-5f3a5300-30af-11eb-90f5-7b923ebad134.png)

Добрый день! Чайник rk-g201s уже установлен и все рабобтает. 
Можно ли рядом установить еще и мультиварку rmc-m40s?
Спасибо за проделанную работу!

**Comment by mavrikkk** [comment]
уже обсуждалось

https://github.com/mavrikkk/ha_kettler/issues/37

**Comment by agospher4eg** [comment]
ок, а в целом моя модель поддерживается? я не нашел полный список поддерживаемых устройств. 
только это
https://github.com/mavrikkk/ha_kettler/blob/master/custom_components/ready4sky/r4sconst.py

**Comment by mavrikkk** [comment]
первая строчка и есть список поддерживаемых устройств. все, что там есть, протестировано сообществом. Все, чего там нет, либо не поддерживается, либо заработает, если протокол одинаков, при минимальных правках. Вашей мультиварки не вижу в списке. Чтобы проверить работоспособность на текущей версии протокола, нужно добавить вашу мультиварку с нужным типом устройства

**Comment by mavrikkk** [comment]
добавил для вас тестовую поддержку. если заработает, то вам повезло. Скачайте новую версию и проверьте

**Comment by agospher4eg** [comment]
Обновился, работает два устройства, перезагружаться боюсь =) Использовал такой же пароль как и на чайнике

**Comment by agospher4eg** [comment]
hot это йогурт, а soup это варка, но в целом топ

**Comment by mavrikkk** [comment]
видимо у вас немного по-другому режимы настроены )
