### ISSUE TITLE
 RK-m170s

### ISSUE THREAD

**Issue by sir90ha** [mavrikkk/ha_kettler#56]
В списке поддерживаемых чайников не указана модель rk_m170s есть только близкая к нему rk_m171s. Соответственно чайник невозможно включить  а вот функции ночника в нем нет, а в интеграции присутствует. И как тогда через ha управлять им.
![Screenshot_2020-12-09-08-09-04-459_io homeassistant companion android](https://user-images.githubusercontent.com/71610337/101587804-02676280-39f6-11eb-9f24-8b2d4cfb2e6c.jpg)
![Screenshot_2020-12-09-08-10-55-669_com android chrome](https://user-images.githubusercontent.com/71610337/101587871-232fb800-39f6-11eb-8411-b3f4383e1b7a.jpg)

**Comment by mavrikkk** [comment]
добавил поддержку. все должно работать
