### ISSUE TITLE
Ошибка после обновления до 2020.12.6: cannot import name 'SERVICE_SET_DATETIME' from 'homeassistant.components.input_datetime'

### ISSUE THREAD

**Issue by Sensei8** [mavrikkk/ha_kettler#57]
Полный текст ошибки:
Unable to prepare setup for platform ready4sky.water_heater: Platform not found (cannot import name 'SERVICE_SET_DATETIME' from 'homeassistant.components.input_datetime' (/usr/src/homeassistant/homeassistant/components/input_datetime/__init__.py)).

Вылечил удалением SERVICE_SET_DATETIME из water_heater.py, с чайником вроде все работает.

**Comment by mavrikkk** [comment]
да, закомментировал эту строку. Все равно пока не использую этот сервис.
Обновите версию или закомментируйте у себя
