### ISSUE TITLE
Изменить частоту опроса BLE эфира

### ISSUE THREAD

**Issue by pavoroby** [mavrikkk/ha_kettler#6]
Если чайник включается механически, на нем самом, информация в HA о том что он изменил свой статус попадает со значительной задержкой (около минуты).

**Comment by mavrikkk** [comment]
да, все верно, интервал опроса чайника по-умолчанию равен 60 сек.
Вы можете это изменить, задав параметр scan_interval в настройках. То есть добавить в конфигурационный файл строку

scan_interval: 10

например...интервал в секундах.
Учтите, что на малинке это приводило к нагрузке на модуль и периодическим отвалам.
Экспериментальным путем можете установить устраивающий вас промежуток времени.

**Comment by pavoroby** [comment]
> scan_interval: 10
Отлично, то что нужно! Благодарю

Будет неплохо добавить эту информацию в README.
