### ISSUE TITLE
Не работает после обновления HA

### ISSUE THREAD

**Issue by bds89** [mavrikkk/ha_kettler#61]
После декабрьского обновления 2020.12.1 у чайника rk210s видна только подсветка, водонагревателя нет. При загрузке HA также выдает сообщение о не запуске интеграии ha_kettler

**Comment by mavrikkk** [comment]
у меня самого чайник давно сломался, поэтому не имею возможности отслеживать изменения. нужен лог, что именно пишет ha, скорее всего внесли изменения в элемент water heater

**Comment by vvvladesss** [comment]
Как получить логи? Такая же фигня :(

**Comment by bds89** [comment]
При загрузке уведоление:
`Invalid config
The following integrations and platforms could not be set up:

ready4sky.water_heater
Please check your config and logs.`
В журнале ошибка:
`Unable to prepare setup for platform ready4sky.water_heater: Platform not found (cannot import name 'SERVICE_SET_DATETIME' from 'homeassistant.components.input_datetime' (/usr/src/homeassistant/homeassistant/components/input_datetime/__init__.py))`

**Comment by mavrikkk** [comment]
вы уверены, что скачали последнюю версию?
SERVICE_SET_DATETIME - эту штуку давно решил, закомментировав

**Comment by mavrikkk** [comment]
на всякий случай вообще удалил эту часть кода... обновите компонент и проверьте

**Comment by bds89** [comment]
Да, сейчас все работает, спасибо! Возможно действительно нужно было просто обновить, была версия от 09.2020.
