### ISSUE TITLE
После обновления 2021/01/27 слетела интеграция, забыл пароль

### ISSUE THREAD

**Issue by Cookies1488** [mavrikkk/ha_kettler#62]
При обновлении до свежей версии интеграции 2021/01/27 слетели сущности чайника, подсветки и статуса.
По совету из readme решил удалить и заново завести интеграцию.
Удалил интеграцию полностью, даже файлы из  custom_components, перезагрузил сервер ХА, заново добавил через HACS интеграцию, перезапустил сервер ХА, через меню интеграций добавил чайник, но при вводе пароля понял что понятия не имею какой вводил до этого.
Но не смущаясь, снял чайник с базы, поставил, подержал кнопочку, чайник "моргнул" всеми лампочками, что по руководству на чайник означает что он забыл про сопряжение, ввел абсолютно рандомный пароль ab64e6f700f75c65 из какого-то описанного тут issue, при запросе о переводе чайника в режим сопряжения сделал как указано, на чайнике начали переливаться индикаторы, нажал подтвердить, иии.....
Сущность чайника появилась, но ошибка в логах five attempts of firstConnect failed
Чайник соответственно не управляется, хотя после подтверждения лампочки бегать перестали, т.е. соединение вроде бы как установлено.

Судя по описанным ранее issue помогает указать пароль который был указан ранее, НО я понятия не имею какой был установлен ранее.
Чем можете помочь?

**Comment by mavrikkk** [comment]
вместо всего этого нужно было только чуточку подождать. Ошибка в обновлении была, которая устранилась спустя несколько часов. Дело в том, что у меня ни одного элемента редмонд не осталось и пишу я совершенно вслепую давно, так что ошибки неизбежны.

Попробуйте еще раз все повторить, только в пароль вбей все f

**Comment by Cookies1488** [comment]
Без изменений, 2021-01-28 18:33:02 WARNING (SyncWorker_14) [custom_components.ready4sky] five attempts of firstConnect failed

**Comment by Cookies1488** [comment]
Еще одно обновление и всё заработадо, спасибо!
