### ISSUE TITLE
ready4sky.fan: Platform not found

### ISSUE THREAD

**Issue by RavenHuginn** [mavrikkk/ha_kettler#63]
После установки интеграции через HACS и добавление чайника RK-G210S
В логе вот такое сообщение
![image](https://user-images.githubusercontent.com/20950826/106359876-ef16aa80-6347-11eb-8819-d7a419293b78.png)

Я что-то не доустановил?

**Comment by mavrikkk** [comment]
все верно. работаю на опережение. исправил fan по совету подписчика, избавившись от deprecated метода, однако оказалось, что по документации он deprecated, а по факту, в последней сборке HA еще не знают об этом...ждите следующей версии HA. либо на следующей неделе верну все на старые рельсы

**Comment by mavrikkk** [comment]
вроде вернул FAN на старые рельсы

**Comment by RavenHuginn** [comment]
Спасибо.
