### ISSUE TITLE
Integration problem!

### ISSUE THREAD

**Issue by SpartiK** [mavrikkk/ha_kettler#64]
Здравствуйте! Плохо знаком с HA, но после добавления репозитория в ХА,(Неважно, через HASC или через Samba) не появляется в настройках интеграции. Перезагружал, удалял, устанавливал.. Ничего не помогает.
В логе только одно упоминание 
2021-02-02 16:47:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ready4sky which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

![image](https://user-images.githubusercontent.com/44985390/106618927-b578b600-6578-11eb-96bf-84781b4bfa1a.png)

**Comment by mavrikkk** [comment]
Попробуйте посмотреть права на папку custom_components и ее содержимое.
Другие сторонние компоненты ставятся через HACS?

**Comment by SpartiK** [comment]
На следующий день появилась интеграция, но после настройки, чайник  не появился в устройствах и опять ошибки ...
Переустанавливал, после  полного удаления. Ничего не меняется...

![Снимок](https://user-images.githubusercontent.com/44985390/106751025-53c85280-6631-11eb-9783-6b5bb9d63a5f.PNG)

**Comment by mavrikkk** [comment]
да, ошибки крайние связаны с тем, что правлю в реальном времени...и вслепую: у меня ни одного устройства не осталось, поэтому вслепую...
сейчас вроде работает. обновите и пробуйте
