### ISSUE TITLE
RK-M216S-E не появляется в устройствах интеграции

### ISSUE THREAD

**Issue by EvgenPavlyuchek** [mavrikkk/ha_kettler#66]
в списке поддерживаемых моделей присутствует
сделал сопряжение - чайник бимкнул, hassio сообщил о создании конфига
устройства нет
перезагрузился
в логах две ошибки
five attempts of firstConnect failed
Connection error

через телефон сопряжение продолжает работать

**Comment by mavrikkk** [comment]
Попробуйте сделать так, чтобы вам ничего не мешало:
1. установите HA и чайник поближе друг к другу. 
2. Отключите от чайника все другие устройства блютус.
3. Запустите интеграцию, выберите чайник из выпадающего списка обнаруженных устройств, убедитесь, что выбрали верное устройство.
4. Убедитесь, что пароль вводите из 16 символов, причем эти символы либо цифры, либо буквы a,b,c,d,e,f
5. На странице с текстом о перевеоде чайника в режим сопряжения переведите чайник в режим сопряжения! Ни раньше, ни позже! Потом нажмите Далее и дождитесь подключения.
Если эти шаги не помогли вам, то есть мысль, что с паролем что то не так. Здесь где то в issues отписывались некоторые, что пароль нужно взять такой же, какой был в офф приложении (у некоторых работает только так). Его можно узнать, сняв лог блютуса и покопавшись wiresharkом.

**Comment by EvgenPavlyuchek** [comment]
так и делал - не работает
требуется ли рут для блютус сниффера ? рекомендуемая программа под андроид без рута ? а то всякой х... в плеймаркете и на 4pda хватает, но снять то, что не знаешь в каком виде должно быть и неизвестно чем - занятие затруднительное

**Comment by EvgenPavlyuchek** [comment]
так и делал, не помогло
как узнать пароль в логе в wireshark ? вижу общение между чайником и телефоном но не вижу чего то похожего на пароль

**Comment by Odmink0** [comment]
Почти такая же проблема: интеграцию завершить невозможно: в выпадающем меню списка устройств - пусто, хотя по блютус чайник доступен и к нему даже можно подключиться с малинки. НО при интеграции - чайника нет, вручную прописать МАС адрес невозможно, хотя во всех инструкциях в Интернете - прописываем вручную..

![image](https://user-images.githubusercontent.com/25773038/110215021-9becc600-7eb8-11eb-92f1-9650f194d7dd.png)

**Comment by Odmink0** [comment]
> Почти такая же проблема: интеграцию завершить невозможно: в выпадающем меню списка устройств - пусто, хотя по блютус чайник доступен и к нему даже можно подключиться с малинки. НО при интеграции - чайника нет, вручную прописать МАС адрес невозможно, хотя во всех инструкциях в Интернете - прописываем вручную..
> 
> ![image](https://user-images.githubusercontent.com/25773038/110215021-9becc600-7eb8-11eb-92f1-9650f194d7dd.png)

Проблемы нет.
Вдруг решается так:
1) cd /srv/homeassistant/lib/python3.7/site-packages/bluepy
2) sudo setcap 'cap_net_raw,cap_net_admin+eip' bluepy-helper
3) sudo systemctl restart home-assistant@homeassistant.service

Чайник начал обнаруживаться и с первого раза подключился.

**Comment by EvgenPavlyuchek** [comment]
> Чайник начал обнаруживаться и с первого раза подключился.

конкретно модель RK-M216S-E ?

**Comment by EvgenPavlyuchek** [comment]
не знаю что значит E

у меня последняя версия hassio на Raspberry Pi 3 32 bit
с выпадающем меню - Имя и адрес устройства - чайник присутствует и выбирается
но после окончания интеграцию в списке устройств не появляется

cd /srv/homeassistant/lib/python3.7/site-packages/bluepy
такая комманда у меня вообще не находит пути cd /srv/homeassistant/lib/python3.7/site-packages/bluepy

можно все ваши шаги по подготовке чайника к интеграции ?
отвязывали от телефона ? выкл-вкл блютуз ? вводили в режим подключения зажимая клавишу питания до установки на базу или после ? мигала ли подсветка в режиме сопряжения ?

**Comment by mavrikkk** [comment]
1. RK-M216S-E такого устройства нет в поддержке. Смотрите список устройств. Если устройства нет в списке, то он считается чайником с типом 1, и работает по этому алгоритму. А ваш чайник вероятнее всего имеет тип 2, как и устройство без Е. Работать естественно не будет. Сейчас я добавил ваше устройство, попробуйте.

2. Пароль должен быть не просто цифренно-буквенный. Он должен быть HEX формата (цифры и ОПРЕДЕЛЕННЫЕ буквы a b c d e f и все). Причем некоторым удается подключить чайник, ТОЛЬКО введя ТОЧНО ТАКОЙ ЖЕ пароль, как в официальном приложении в тлф (узнать его можно, только сняв лог с блютуса на андроид устройстве).

3. Отвязывать от тлф необязательно (но держать коннект с тлф во время подключения к HA не нужно). Закройте и убейте приложение и/или выключите блютус на тлф. Но для чистоты эксперимента можно и отвязать, надежнее.

4. Нужно действовать по инструкции, как указано в интеграции. Устанавливаете чайник, запускаете интеграцию, выбираете устройство, вводите пароль и тд, нажимаете далее. Там вам напишут когда и как перевести чайник в режим сопряжения.

**Comment by EvgenPavlyuchek** [comment]
спс, заработало
учитывая что на оф сайте и в продаже я видел чайники только с приставкой E - полагал без нее и не бывает, а в списке просто унификация
видимо локализация названий в разных странах

**Comment by lukaszliniewicz** [comment]
Could someone please explain to me how to extract the password from the BT log? I downloaded the BT HCI log from my phone and opened it with Wireshark, but I'm a novice and I have no idea what to do. Thanks!

Кто-нибудь может объяснить мне, как извлечь пароль из лога BT? Я загрузил лог BT HCI с моего телефона и открыл его с помощью Wireshark, но я новичок и понятия не имею, что делать. Спасибо!
