### ISSUE TITLE
Вопрос по установке

### ISSUE THREAD

**Issue by VadimSK** [mavrikkk/ha_kettler#68]
Приветствую!
Может глупый вопрос... Но тем не менее.
Как добавить интеграцию в Home Assistant?
В Настройки->Интеграции не обнаруживается ready4sky
В HACS аналогично. Ready4sky поиск не находит. Попробовал старое название, нет успеха.
Заранее, спасибо за помощь!

**Comment by ARNik** [comment]
Добавь репозиторий в HACS

**Comment by VadimSK** [comment]
Это понятно, но как его название? Как только не пробовал уже искать.
НАСS->add repositories->ready4sky (sky,ready, kettler и т.д.) Итог один: Не найдено репозиторий, соответствующих фильтру

**Comment by mavrikkk** [comment]
вот это вставить в add repositories:
https://github.com/mavrikkk/ha_kettler

**Comment by VadimSK** [comment]
Я не знаю, как это можно объяснить, но твой репозиторий не находится:
https://cloud.mail.ru/public/miq6/ZvnBEiPEA

**Comment by ARNik** [comment]
Нажми три точки в правом верхнем углу и добавь репозиторий.

**Comment by VadimSK** [comment]
Прошу прощения, конечно, но там нельзя добавить...
https://cloud.mail.ru/public/4x7n/p4KbcWEKG

**Comment by ARNik** [comment]
![image](https://user-images.githubusercontent.com/3407744/110788236-6b71a700-827f-11eb-8ff7-6d3006b64259.png)

**Comment by VadimSK** [comment]
Как же жёстко я затупил... Огромное спасибо за терпение и понимание!!!
