### ISSUE TITLE
Работа чайника совместно с Алисой

### ISSUE THREAD

**Issue by TimpP-Spb** [mavrikkk/ha_kettler#74]
Столкнулся с такой проблемой, когда в алисе запрашиваешь текущую температуру, то сообщается температура которая выставлена для поддержания. Можно ли как то это поправить, или в каком направлении копать?

Стоит интеграция НА+Yandex Smart+Redmond Sky

**Comment by HepoH3** [comment]
В атрибутах сущности чайника есть текущая температура. Железобетонным вариантом будет создание template сенсора, который будет прокинут в алису.
![](https://puu.sh/HHXBG/c6ab8caebd.png)

**Comment by HepoH3** [comment]
Вероятно, дело в том, что выставленная температура поддержания называется temperature, вот поэтому именно она и озвучивается. Если это действительно так, то переименование атрибутов:

- `temperature -> temperature_control_value`
- `current_temperature -> temperature`

приведет к желаемому эффекту.
