### ISSUE TITLE
Ошибка при установке в hacs

### ISSUE THREAD

**Issue by HepoH3** [mavrikkk/ha_kettler#75]
После установки интеграции в hacs и перезагрузки сервера появляется ошибка:
` <Integration mavrikkk/ha_kettler> No file found 'custom_components/helper/manifest.json' `
Если зайти в папку custom_components, то папки ready4sky там видно не будет.
Причем саму интеграцию уже не удалить, если зарыться в логи, то можно будет найти
```
2021-05-19 09:07:14 ERROR (MainThread) [custom_components.hacs] <Integration mavrikkk/ha_kettler> No file found 'custom_components/helper/manifest.json'
2021-05-19 09:07:14 ERROR (MainThread) [custom_components.hacs] <Integration mavrikkk/ha_kettler> Missing domain
2021-05-19 09:07:14 ERROR (MainThread) [custom_components.hacs] Could not uninstall
```
Полагаю, дело в недавно влитом реквесте.

**Comment by ARNik** [comment]
![image](https://user-images.githubusercontent.com/3407744/118768867-2de55780-b888-11eb-8670-00ebe5ec1d46.png)
![image](https://user-images.githubusercontent.com/3407744/118768945-45244500-b888-11eb-8af9-c2bb771e213d.png)

**Comment by pavoroby** [comment]
После установки через HACS компонент исчезает из директории custom_components. Получается что работать нечему. Лично я нашел у себя бекапы до обновления и восстановил из них сам компонент ready4sky. 
Пока автор не вышел на связь с решением этой проблемы, можно воспользоваться https://www.dropbox.com/s/cad07i1x14uwsdo/ready4sky.zip, развернув его в custom_components.

**Comment by mavrikkk** [comment]
вызываем @siriuske  на помощь ) его пулл-реквест. Я в шапке давно разместил, что у меня не осталось устройств вообще и мне тестировать не на чем.

**Comment by mavrikkk** [comment]
я пока попробовал просто перенести его хелпер в основную папку с изменениями в подключаемых путях. попробуйте, возможно этого будет достаточно

**Comment by HepoH3** [comment]
> 
> 
> я пока попробовал просто перенести его хелпер в основную папку с изменениями в подключаемых путях. попробуйте, возможно этого будет достаточно

Минуту, сделаю бэкап и проверю.

**Comment by HepoH3** [comment]
Вроде работает, хотя сервер как-то подозрительно долго перезагружался. Чайник включился, больше тестить не могу — на работу надо идти срочно.

**Comment by mavrikkk** [comment]
ждем подтверждения, как сможете ) может еще кто отпишется

**Comment by HepoH3** [comment]
Так, я вернулся. Пока не было дома, в логе появились такие вот ошибки:
```
Logger: custom_components.ready4sky.decorators
Source: custom_components/ready4sky/decorators.py:17
Integration: ready4sky (documentation)
First occurred: 14:07:27 (2725 occurrences)
Last logged: 15:37:19

    5 attempts of __enter__ failed. Reason: Failed to connect to peripheral ed:99:2c:79:90:a3, addr type: random
    5 attempts of modeUpdate failed. Reason: 'NoneType' object has no attribute 'make_request'
```
Перезагрузил сервер — по прежнему очень долго перезагружается. После перезагрузки увидел такие вот ошибки:
 
```
Failed to to call /ingress/validate_session -
15:42:18 – (ОШИБКА) Home Assistant Supervisor - первое сообщение получено 15:42:18 и повторялось 4 раз
```

```
/ingress/validate_session return code 401
15:42:18 – (ОШИБКА) Home Assistant Supervisor - первое сообщение получено 15:42:18 и повторялось 4 раз
```
Не могу сказать было ли такое до обновления — пользовался вашей интеграцией где-то год назад, но поскольку блютуз-модуль в компьютере был один, и нужен был для подключения наушников, в итоге забил. Сегодня приехал еще один, который планировал прокидывать в HA, после чего решил продолжить пользоваться вашей интеграцией.

Помимо прочего, в логе хоста вижу ещё вот такие ошибки:

```
[15083.631405] Bluetooth: hci0: command 0x2016 tx timeout
[15111.679065] Bluetooth: hci0: unexpected event for opcode 0x0016
[15111.681872] Bluetooth: hci0: unexpected event for opcode 0x2016
[15583.338305] Bluetooth: hci0: command 0x200c tx timeout
[15623.466007] Bluetooth: hci0: command 0x2016 tx timeout
[15623.487095] Bluetooth: hci0: unexpected event for opcode 0x0016
[15623.490170] Bluetooth: hci0: unexpected event for opcode 0x2016
[16008.102078] Bluetooth: hci0: command 0x0406 tx timeout
[20791.937531] Bluetooth: hci0: unexpected event for opcode 0x0406
[20791.940215] Bluetooth: hci0: unexpected event for opcode 0x0406
```
Накидываю если что вообще всё что вижу, скорей всего то что последнее скинуто, и таймауты подключения — не связаны с обновлением и не особо критичны.

После удаления интеграции сервер загружается в нормальном режиме.
Если закинуть архив, предыдущей версии интеграции, скинутый @pavoroby, сервер загружается в обычном режиме. В общем, я бы пока сделал откат последних коммитов до получения стабильной версии.

**Comment by HepoH3** [comment]
Если вам будет всё ещё интересно работать с этой интеграцией, и проблема только в отсутствии чайника, готов перевести вам 2к рублей на приобретение нового.

**Comment by mavrikkk** [comment]
> Если вам будет всё ещё интересно работать с этой интеграцией

Идей много! Начиная с глобальной "замена библиотеки на настоящую асинхронную", добавление новых устройств и фич и заканчивая рефакторингом и кучей оптимизаций. Однако после смерти чайника пыл немного поостыл ) А потом случились и другие события, так что теперь и времени меньше стало намного ) Надеюсь, что кто-то с горящими глазами возьмется за начатую инициативу и доведет все до ума. 



> готов перевести вам 2к рублей

спасибо, щедро, но отсутствие чайника, как вы уже понимаете,  это -  не главная причина )

**Comment by mavrikkk** [comment]
> В общем, я бы пока сделал откат последних коммитов

Да, сейчас попробую вернуть все взад ))

**Comment by HepoH3** [comment]
> Надеюсь, что кто-то с горящими глазами возьмется за начатую инициативу и доведет все до ума.
Я мог бы предложить свою кандидатуру конечно — мне это интересно, прикладные скрипты на пайтоне я писал, но вот что-то такое, что интегрируется в другой проект — нет, и не очень понимаю как это всё работает. В принципе, с вашей поддержкой это могло бы сработать и для меня самого это было бы полезным опытом, но если честно — подобное моё предложение было бы опрометчивым поступком, у меня сейчас диплом и всегда будут находиться причины, почему не хватает времени на реальную поддержку интеграции)

**Comment by mavrikkk** [comment]
> У меня на последней версии постоянные ошибки
> `2021-05-19 23:57:38 ERROR (MainThread) [custom_components.ready4sky] Connect to d1:ac:38:5f:52:f0 through device hci0 failed `
> Есть предложения?

есть:
1. уменьшить расстояние между приемником и передатчиком
2. если малинка, то не использовать встроенный блютус, а купить хороший внешний
3. если внешний, то убедиться, что он хороший
4. убедиться, что ваш чайник (или какое другое устройство redmond) есть в списке официально поддерживаемых.

если все это перепробовали и ничего не помогло, то предложений больше нет ((

**Comment by mavrikkk** [comment]
> Есть предложения?

Если ничего из вышеперечисленного вас не устраивает и есть еще какие доп сведения, то открывайте новый issue. Данный был предназначен именно для ошибки, связанной с принятием нового пулл  реквеста.
