### ISSUE TITLE
Controlling the RK-M216S-E kettle

### ISSUE THREAD

**Issue by mkielarv2** [mavrikkk/ha_kettler#77]
Hello, I have successfully added the integration and connected to my RK-M216S-E skykettle yet it shows only 2 status entities, but no control entities:
![image](https://user-images.githubusercontent.com/30040204/124168659-bb31e380-daa5-11eb-98ab-00c6d051d510.png)
How can I control the kettle (most important is remote start)?

**Comment by mavrikkk** [comment]
click on "Kettle RK-M216S-E" and you'll see an additional information with temperature control and "on"-"off" buttons

**Comment by mkielarv2** [comment]
Thanks, I have missed that. I have another question, how do you control the kettle via call-service client like node red? I only see the water_heater.set_temperature option. How do I turn it on?

**Comment by mavrikkk** [comment]
set_operation_mode
