### ISSUE TITLE
Поддержка климатической станции RSC-51S

### ISSUE THREAD

**Issue by artt652** [mavrikkk/ha_kettler#82]
Здравствуйте, хотелось бы иметь возможность получать в HA показания сенсоров с умной климатической станции RSC-51S, есть ли такая возможность?

**Comment by mavrikkk** [comment]
Здравствуйте. Возможность есть. Нужно только знать протокол обмена )
1. Это можно сделать, имея устройство на руках, к сожалению его нет у меня.
2. Либо вы сами получите протокол обмена и вышлите его мне, а я добавлю.

Во втором случае вам нужен  смартфон на андроид с поддержкой записи лога блютус, умение выполнять инструкции наподобие таких ( https://github.com/mavrikkk/ha_kettler/issues/18 ), и время.
Вкратце нужно: перечень всех функций станции (данные, переключатели и тд и тп). Потом пишете лог по каждой из этих функций/датчиков с документированием реальных параметров. Потом высылаете все мне. Я восстанавливаю протокол и добавляю поддержку в свободное время.

**Comment by artt652** [comment]
Здравствуйте, лог снял, видео с экрана записал. Похоже что имеется только один переключатель для сброса калибровки датчика качества воздуха, а сама станция после подключения просто предает данные с сенсоров (температура, влажность, давление , кач-во воздуха). 
Также имеется функция включения /выключения дополнительных устройств по изменению измеряемых параметров, но возможности проверить ее не было.

**Comment by artt652** [comment]
Вопрос закрыт, реализовано на [ESP32-R4sGate-for-Redmond](https://github.com/alutov/ESP32-R4sGate-for-Redmond/issues/50).
