### ISSUE TITLE
Где вводить MAC адрес?

### ISSUE THREAD

**Issue by DIMMonchik** [mavrikkk/ha_kettler#87]
Где вводить MAC адрес? У меня нет такого поля
![image](https://user-images.githubusercontent.com/38500475/151657480-3efeabc5-e6aa-413b-a1cc-037e0ac48ec7.png)

**Comment by mavrikkk** [comment]
посмотрите тут (https://github.com/mavrikkk/ha_kettler/issues/85)
у меня все в порядке. Возможно у вас не нашлось ни одного устройства
