### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by Cookies1488** [mavrikkk/ha_kettler#88]
Entity sensor.status_rk_g200s (<class 'custom_components.ready4sky.sensor.RedmondSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity water_heater.kettle_rk_g200s (<class 'custom_components.ready4sky.water_heater.RedmondWaterHeater'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mavrikkk** [comment]
corrected
