### ISSUE TITLE
REDMOND SkyCenter 11S

### ISSUE THREAD

**Issue by dfymdfym** [mavrikkk/ha_kettler#89]
Здравствуйте. Я новичок и может вопрос мой очевиден для всех, но решение пока найти мне не удалось. Есть ли какой-то способ привязать шлюз SkyCenter 11S к home assistant по wi-fi не теряя управление из ready for sky. Я вобщем-то и без потери управления привязать не могу :) Кроме Вас этим вопросом для HA никто не занимается.

**Comment by artt652** [comment]
SkyCenter 11S сам по себе никуда не прокидывается, это же шлюз, у него чисто передаточная функция.

А этот компонент работает **без** облака, даже более того: вместе с облаком правильно работать не будет.  

Насчет не теряя управление из ready for sky думается что можно прокинуть аккаунт только через сторонний УД (например яндекс или гугл) и соответствующие интеграции для HA. - но это довольно непростой вариант + не факт что нужное устройство будет поддерживаться на 100%.

Также думаю стоит обратить внимание на еще 2 проекта от тов. @alutov и @ClusterM, т.к активное развитие данной интеграции приостановлено.

**Comment by dfymdfym** [comment]
Спасибо за совет. Буду изучать
