### ISSUE TITLE
Отключение подсветки

### ISSUE THREAD

**Issue by Marat0Sh** [mavrikkk/ha_kettler#9]
Добрый день!
Отключаю пульсирующую подсветку на чайнике с помощью переключателя `redmondusebacklight`, отключается корректно, но после перезагрузки Home Assistant она вновь включается, как то можно запомнить эту настройку?

**Comment by mavrikkk** [comment]
это значение по-умолчанию. Можете себе сделать выкл по умолчанию. Для этого нужно открыть файл __init__.py любым текстовым редактором и заменить в функции __init__
self._usebacklight = True
на
self._usebacklight = False

**Comment by Marat0Sh** [comment]
Спасибо, получилось!
