### ISSUE TITLE
Random password doesn't work, how to extract the one used by the app from HCI log?

### ISSUE THREAD

**Issue by lukaszliniewicz** [mavrikkk/ha_kettler#92]
Could someone please explain to me how to extract the password from the BT log? I downloaded the BT HCI log from my phone and opened it with Wireshark, but I'm a novice and I have no idea what to do. Thanks!

Кто-нибудь может объяснить мне, как извлечь пароль из лога BT? Я загрузил лог BT HCI с моего телефона и открыл его с помощью Wireshark, но я новичок и понятия не имею, что делать. Спасибо!

**Comment by Psytoshgen** [comment]
та же беда, написано что RMC-M223S поддерживается, но не алгоритмов подключения, ни где пароль выдернуть не написано...

**Comment by Psytoshgen** [comment]
found solution
https://crypt-online.ru/crypts/text2hex/
just make 8 symbol pass and convert it to hex ascii

**Comment by Psytoshgen** [comment]
не пригодилось
создал пароль на 8 символов и перевел его в ascii hex тут https://crypt-online.ru/crypts/text2hex/
