### ISSUE TITLE
2022.7 Setup failed for custom integration ready4sky: Requirements for ready4sky not found: ['bluepy']

### ISSUE THREAD

**Issue by pticavorobey** [mavrikkk/ha_kettler#95]
После обновления на 2022.7 Core (Docker) стали недоступны пакеты bluepy и pybluez [#pull](https://github.com/home-assistant/core/pull/73830). Разработчики HA обязывают перейти  на библиотеку [Bleak](https://pypi.org/project/bleak/)

**Comment by mavrikkk** [comment]
самое интересное, что я когда то активно занимался разработкой данной интеграции и писал напрямую им с просьбой перейти на классную асинхронную библиотеку bleak. Это бы решило кучу проблем и позволило бы правильную асинхронность добавить в интеграцию...мне не ответили...теперь вот перешли, но я уже не занимаюсь поддержкой данного проекта (пропали все мои устройства redmond). Вроде тут кто то недавно форкнул мой проект и обещался подхватить знамя. Попробуйте написать ему, переход на bleak - это круто на самом деле, хоть и придется переписать достаточно кода

**Comment by mavrikkk** [comment]
вот https://github.com/mavrikkk/ha_kettler/issues/94

**Comment by pticavorobey** [comment]
@XNicON

**Comment by XNicON** [comment]
Ну хз, знамя на самом деле не перехватывал, просто починил свой чайник, поделился. Обновляться думаю скоро буду на 2022.7 тогда и гляну.
похоже остался только pybluez и pygatt, а bleak не увидел

**Comment by XNicON** [comment]
Установку bleak не увидел нигде, но в самом образе вроде есть (и уже как минимум в 2022.6) и нашёл в заметке к релизу, действительно пожелания использования.
Не просто оказалось, но перевёл на bleak, убрал лишнего, доработал и стало работать по скорости и надёжности как приложение с телефона, теперь в реальном времени разогрев и всё, что он там пришлёт (чайник).
можно сказать вопрос снят, эту тему можно закрывать.

к сожалению устройства не получится сохранить, появятся новые, так что предыдущею версию следует удалить

**Comment by pticavorobey** [comment]
Решение обозначенной в issue темы является использование форка https://github.com/XNicON/hassio-r4s
