### ISSUE TITLE
2022.8 (пока beta) имеет поддержку push для bt устройств

### ISSUE THREAD

**Issue by notabene00** [mavrikkk/ha_kettler#96]
Пока не вникал что к чему, но если дописать поддержку, должно сильно повысить стабильность данной интеграции
https://rc.home-assistant.io/blog/2022/07/27/release-20228/#first-class-bluetooth-support

**Comment by mavrikkk** [comment]
duplicate of https://github.com/mavrikkk/ha_kettler/issues/99

**Comment by notabene00** [comment]
забавно `jul 29` быть дубликатом `sep 11` issue 
и жалко, что разработка больше не ведется
впрочем, поставил аналогичный компонент от @clusterm
не без косяков, но работает

**Comment by mavrikkk** [comment]
насколько я знаю, компонента уже не бета. поэтому из двух оставил более свежее без упоминания бета ) надеюсь, я не задел вас лично этим )
