### ISSUE TITLE
Нельзя выгрузить репозиторий

### ISSUE THREAD

**Issue by tina80lvl** [mavrikkk/ha_kettler#98]
Пытаюсь подключить компонент к HomeAssistant, выдаёт ошибку:
![Screenshot 2022-09-08 at 17 39 38](https://user-images.githubusercontent.com/27859234/189151822-a1970739-a860-4429-811a-22a4e0d07c61.png)

**Comment by mavrikkk** [comment]
устанавливается интеграция, а не addon. Либо вручную, либо через HACS.
![image](https://user-images.githubusercontent.com/42514734/197710927-241ab272-268b-4c43-9c17-61fff3e3bce9.png)
